---
title: " The data analysis of Chinese medicine intake situation in Shanghai"
author: "Xiaohui Xu"
date: "2020/10/28"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning=FALSE, message=FALSE)
```


```{r retrieve data, echo=FALSE, message=FALSE, warning=FALSE}
library("RMySQL")# Load RMySQL package
library("utf8")# Load utf8 package
library("DBI")# Load DBI package
library("MASS")# Load MASS package    
library("survival")# Load survival package
library("ggplot2")# Load ggplot2 package
library("knitr")# Load knitr package
library("dplyr")# Load dplyr package
library("kableExtra")# Load kableExtra package
library("reshape2")#  Load reshape2 package
library("stringr")# Load stringr package
library("tidyverse")# Load tidyverse package
#链接数据库
tryCatch(mysqlconnection <- dbConnect(MySQL(), user = 'root', password = '5mayday', 
                                      dbname = 'ctm', host = 'localhost',DBMSencoding="UTF8")) 
tryCatch(dbSendQuery(mysqlconnection, 'SET NAMES gbk'))   
memory.limit(102400)
# data retrieve 
kq2019<-dbReadTable(mysqlconnection, "kq2019")
wansc2019<-dbReadTable(mysqlconnection, "wansc2019")
hq2019_raw<-dbReadTable(mysqlconnection, "hq2019_raw")
```

```{r All data clean, echo=FALSE}
## data clean
t <- which(stringr::str_detect(wansc2019$CMN,"蜈蚣"))
t <- which(stringr::str_detect(wansc2019$CMN,"坎炁"))
t <- which(stringr::str_detect(wansc2019$CMN,"抗变汤"))
t <- which(stringr::str_detect(wansc2019$CMN,"健脾抗瘤汤"))
wansc2019[t,]$DD <- 1
t <- which(stringr::str_detect(wansc2019$CMN,"川贝粉已付"))
wansc2019[t,]$DD <- 30
t <- which(stringr::str_detect(wansc2019$CMN,"(2015)"))
wansc2019[t,]$DD <- 1
t <- which(stringr::str_detect(wansc2019$CMN,"（2019）"))
wansc2019[t,]$DD <- 1
t <- which(stringr::str_detect(wansc2019$DD,"2*10包"))
wansc2019[t,]$DD <- 20
t <- which(stringr::str_detect(wansc2019$DD,"2*7袋/盒"))
wansc2019[t,]$DD <- 14
wansc2019$DD <- gsub("[^0-9\\.]","",wansc2019$DD)
## The unique identification number merge of hq2019 and wansc2019
### hq2019_raw
hq2019_raw$H_Name <- str_c(hq2019_raw$H ,sep = ";", hq2019_raw$Name )
### wansc2019
wansc2019$ID <- wansc2019$Phone
sub <- which(is.na(wansc2019$ID))
wansc2019[sub,]$ID  <- wansc2019[sub,]$Tel
wansc2019$ID_Name <- str_c(wansc2019$Name,sep = ";",wansc2019$ID)
```
```{r 黄芪 data clean, echo=FALSE}

# --------retrieve the 黄芪 data of wansc2109--------
t <- which(stringr::str_detect(wansc2019$CMN,"黄芪"))
黄芪 <- wansc2019[t,]
黄芪$DD <- as.numeric(黄芪$DD)
黄芪$days <- as.numeric(黄芪$days)
黄芪$ds <- 黄芪$DD*黄芪$days
黄芪$ds <- as.numeric(黄芪$ds)
det1<-as.data.frame(黄芪[,c("ID_Name","ds","CMN","days")])
#生成ID_Name为识别号的数据框 
wansc2019_intakesum<-reshape2::dcast(det1, 	
                           ID_Name ~ CMN,
                           value.var = "ds", sum)	
黄芪_wansc2019_intakesum<-as.vector(as.matrix(wansc2019_intakesum$`黄芪`))
wansc2019_dayssum<-reshape2::dcast(det1,
                      ID_Name ~  CMN,
                      value.var = "days",sum)
黄芪_wansc2019_dayssum<-as.vector(as.matrix(wansc2019_dayssum$`黄芪`))
#合并黄芪的消费量和days表格
wansc2019_intakemergedays <- merge(x=wansc2019_intakesum, y=wansc2019_dayssum,
                         by.x="ID_Name",
                         by.y="ID_Name"
)
options(digits = 3)
wansc2019_intakemergedays$standard <- wansc2019_intakemergedays$黄芪.x/wansc2019_intakemergedays$黄芪.y
黄芪_dailyintake <- as.vector(as.matrix(wansc2019_intakemergedays$standard))

# --------retrieve the 黄芪 data of hq2019_raw--------
黄芪 <- hq2019_raw[hq2019_raw$CMN =="黄芪",]
黄芪$DD <- as.numeric(黄芪$DD)
黄芪$days <- as.numeric(黄芪$days)
黄芪$total <- 黄芪$DD*黄芪$days
黄芪$total <- as.numeric(黄芪$total)
det1<-as.data.frame(黄芪[,c("H_Name","total","CMN","days")])
#生成H_Name为识别号的数据框
hq2019_raw_intakesum<-reshape2::dcast(det1, 	
                                  H_Name ~ CMN,
                                  value.var = "total", sum)	
黄芪_hq2019_raw_intakesum<-as.vector(as.matrix(hq2019_raw_intakesum$`黄芪`))
hq2019_raw_dayssum<-reshape2::dcast(det1,
                                H_Name ~  CMN,
                                value.var = "days",sum)
黄芪_hq2019_raw_dayssum<-as.vector(as.matrix(hq2019_raw_dayssum$`黄芪`))
#合并黄芪的消费量和days表格
hq2019_raw_intakemergedays <- merge(x=hq2019_raw_intakesum, y=hq2019_raw_dayssum,
                                by.x="H_Name",
                                by.y="H_Name"
)
options(digits = 3)
hq2019_raw_intakemergedays$standard <- hq2019_raw_intakemergedays$黄芪.x/hq2019_raw_intakemergedays$黄芪.y
黄芪_hq2019_raw_dailyintake <- as.vector(as.matrix(hq2019_raw_intakemergedays$standard))

# --------retrieve the 黄芪 data of kq2019--------
黄芪 <- kq2019[kq2019$CMN =="黄芪",]
黄芪$DD <- as.numeric(黄芪$DD)
黄芪$days <- as.numeric(黄芪$days)
黄芪$total <- 黄芪$DD*黄芪$days
黄芪$total <- as.numeric(黄芪$total)
det1<-as.data.frame(黄芪[,c("Name","total","CMN","days")])
#生成Name为识别号的数据框
kq2019_intakesum<-reshape2::dcast(det1, 	
                                  Name ~ CMN,
                                  value.var = "total", sum)	
黄芪_kq2019_intakesum<-as.vector(as.matrix(kq2019_intakesum$`黄芪`))
kq2019_dayssum<-reshape2::dcast(det1,
                                Name ~  CMN,
                                value.var = "days",sum)
黄芪_kq2019_dayssum<-as.vector(as.matrix(kq2019_dayssum$`黄芪`))
#合并黄芪的消费量和days表格
kq2019_intakemergedays <- merge(x=kq2019_intakesum, y=kq2019_dayssum,
                                by.x="Name",
                                by.y="Name"
)
options(digits = 3)
kq2019_intakemergedays$standard <- kq2019_intakemergedays$黄芪.x/kq2019_intakemergedays$黄芪.y
黄芪_kq2019_dailyintake <- as.vector(as.matrix(kq2019_intakemergedays$standard))

#将三个厂的数据结合
colnames(hq2019_raw_intakemergedays) <- c("Name","intakesum","days","standard")
colnames(wansc2019_intakemergedays) <- c("Name","intakesum","days","standard")
colnames(kq2019_intakemergedays) <- c("Name","intakesum","days","standard")
hq2019_raw_kq2019_intakemergedays <- rbind(hq2019_raw_intakemergedays,kq2019_intakemergedays)
wansc2019_hq2019_raw_kq2019_intakemergedays <- rbind(hq2019_raw_kq2019_intakemergedays,wansc2019_intakemergedays)
colnames(wansc2019_hq2019_raw_kq2019_intakemergedays) <- c("Name","intakesum","days","standard")
write.table(wansc2019_hq2019_raw_kq2019_intakemergedays,file="E:\\R export\\Personal intake disturbution of 黄芪 .csv",row.names = F,col.names = T,sep=",")
```


<center>
```{r 黄芪 quantile calculate, echo=FALSE}
# Calculate the 黄芪 quantile of annual_intake
options(digits=4)
黄芪_wansc2019_hq2019_raw_kq2019_intakesum <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$intakesum))
黄芪_annual_intake<-c(quantile(黄芪_wansc2019_hq2019_raw_kq2019_intakesum, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(黄芪_wansc2019_hq2019_raw_kq2019_intakesum))
# Calculate the 黄芪 quantile of intake_days
黄芪_wansc2019_hq2019_raw_kq2019_dayssum <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$days))
黄芪_intake_days <- c(quantile(黄芪_wansc2019_hq2019_raw_kq2019_dayssum, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(黄芪_wansc2019_hq2019_raw_kq2019_dayssum))
# Calculate the 黄芪 quantile of daily_intake
黄芪_wansc2019_hq2019_raw_kq2019_dailyintake <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$standard))
黄芪_daily_intake <- c(quantile(黄芪_wansc2019_hq2019_raw_kq2019_dailyintake, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(黄芪_hq2019_raw_dailyintake))
```

```{r 薏苡仁 data clean, echo=FALSE}

# --------retrieve the 薏苡仁 data of wansc2109--------
t <- which(stringr::str_detect(wansc2019$CMN,"薏苡仁"))
薏苡仁 <- wansc2019[t,]
薏苡仁$DD <- as.numeric(薏苡仁$DD)
薏苡仁$days <- as.numeric(薏苡仁$days)
薏苡仁$ds <- 薏苡仁$DD*薏苡仁$days
薏苡仁$ds <- as.numeric(薏苡仁$ds)
det1<-as.data.frame(薏苡仁[,c("ID_Name","ds","CMN","days")])
#生成ID_Name为识别号的数据框 
wansc2019_intakesum<-reshape2::dcast(det1, 	
                           ID_Name ~ CMN,
                           value.var = "ds", sum)	
薏苡仁_wansc2019_intakesum<-as.vector(as.matrix(wansc2019_intakesum$`薏苡仁`))
wansc2019_dayssum<-reshape2::dcast(det1,
                      ID_Name ~  CMN,
                      value.var = "days",sum)
薏苡仁_wansc2019_dayssum<-as.vector(as.matrix(wansc2019_dayssum$`薏苡仁`))
#合并薏苡仁的消费量和days表格
wansc2019_intakemergedays <- merge(x=wansc2019_intakesum, y=wansc2019_dayssum,
                         by.x="ID_Name",
                         by.y="ID_Name"
)
options(digits = 3)
wansc2019_intakemergedays$standard <- wansc2019_intakemergedays$薏苡仁.x/wansc2019_intakemergedays$薏苡仁.y
薏苡仁_dailyintake <- as.vector(as.matrix(wansc2019_intakemergedays$standard))

# --------retrieve the 薏苡仁 data of hq2019_raw--------
薏苡仁 <- hq2019_raw[hq2019_raw$CMN =="薏苡仁",]
薏苡仁$DD <- as.numeric(薏苡仁$DD)
薏苡仁$days <- as.numeric(薏苡仁$days)
薏苡仁$total <- 薏苡仁$DD*薏苡仁$days
薏苡仁$total <- as.numeric(薏苡仁$total)
det1<-as.data.frame(薏苡仁[,c("H_Name","total","CMN","days")])
#生成H_Name为识别号的数据框
hq2019_raw_intakesum<-reshape2::dcast(det1, 	
                                  H_Name ~ CMN,
                                  value.var = "total", sum)	
薏苡仁_hq2019_raw_intakesum<-as.vector(as.matrix(hq2019_raw_intakesum$`薏苡仁`))
hq2019_raw_dayssum<-reshape2::dcast(det1,
                                H_Name ~  CMN,
                                value.var = "days",sum)
薏苡仁_hq2019_raw_dayssum<-as.vector(as.matrix(hq2019_raw_dayssum$`薏苡仁`))
#合并薏苡仁的消费量和days表格
hq2019_raw_intakemergedays <- merge(x=hq2019_raw_intakesum, y=hq2019_raw_dayssum,
                                by.x="H_Name",
                                by.y="H_Name"
)
options(digits = 3)
hq2019_raw_intakemergedays$standard <- hq2019_raw_intakemergedays$薏苡仁.x/hq2019_raw_intakemergedays$薏苡仁.y
薏苡仁_hq2019_raw_dailyintake <- as.vector(as.matrix(hq2019_raw_intakemergedays$standard))

# --------retrieve the 薏苡仁 data of kq2019--------
薏苡仁 <- kq2019[kq2019$CMN =="薏苡仁",]
薏苡仁$DD <- as.numeric(薏苡仁$DD)
薏苡仁$days <- as.numeric(薏苡仁$days)
薏苡仁$total <- 薏苡仁$DD*薏苡仁$days
薏苡仁$total <- as.numeric(薏苡仁$total)
det1<-as.data.frame(薏苡仁[,c("Name","total","CMN","days")])
#生成Name为识别号的数据框
kq2019_intakesum<-reshape2::dcast(det1, 	
                                  Name ~ CMN,
                                  value.var = "total", sum)	
薏苡仁_kq2019_intakesum<-as.vector(as.matrix(kq2019_intakesum$`薏苡仁`))
kq2019_dayssum<-reshape2::dcast(det1,
                                Name ~  CMN,
                                value.var = "days",sum)
薏苡仁_kq2019_dayssum<-as.vector(as.matrix(kq2019_dayssum$`薏苡仁`))
#合并薏苡仁的消费量和days表格
kq2019_intakemergedays <- merge(x=kq2019_intakesum, y=kq2019_dayssum,
                                by.x="Name",
                                by.y="Name"
)
options(digits = 3)
kq2019_intakemergedays$standard <- kq2019_intakemergedays$薏苡仁.x/kq2019_intakemergedays$薏苡仁.y
薏苡仁_kq2019_dailyintake <- as.vector(as.matrix(kq2019_intakemergedays$standard))

#将三个厂的数据结合
colnames(hq2019_raw_intakemergedays) <- c("Name","intakesum","days","standard")
colnames(wansc2019_intakemergedays) <- c("Name","intakesum","days","standard")
colnames(kq2019_intakemergedays) <- c("Name","intakesum","days","standard")
hq2019_raw_kq2019_intakemergedays <- rbind(hq2019_raw_intakemergedays,kq2019_intakemergedays)
wansc2019_hq2019_raw_kq2019_intakemergedays <- rbind(hq2019_raw_kq2019_intakemergedays,wansc2019_intakemergedays)
colnames(wansc2019_hq2019_raw_kq2019_intakemergedays) <- c("Name","intakesum","days","standard")
write.table(wansc2019_hq2019_raw_kq2019_intakemergedays,file="E:\\R export\\Personal intake disturbution of 薏苡仁 .csv",row.names = F,col.names = T,sep=",")
```


<center>
```{r 薏苡仁 quantile calculate, echo=FALSE}
# Calculate the 薏苡仁 quantile of annual_intake
options(digits=4)
薏苡仁_wansc2019_hq2019_raw_kq2019_intakesum <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$intakesum))
薏苡仁_annual_intake<-c(quantile(薏苡仁_wansc2019_hq2019_raw_kq2019_intakesum, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(薏苡仁_wansc2019_hq2019_raw_kq2019_intakesum))
# Calculate the 薏苡仁 quantile of intake_days
薏苡仁_wansc2019_hq2019_raw_kq2019_dayssum <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$days))
薏苡仁_intake_days <- c(quantile(薏苡仁_wansc2019_hq2019_raw_kq2019_dayssum, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(薏苡仁_wansc2019_hq2019_raw_kq2019_dayssum))
# Calculate the 薏苡仁 quantile of daily_intake
薏苡仁_wansc2019_hq2019_raw_kq2019_dailyintake <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$standard))
薏苡仁_daily_intake <- c(quantile(薏苡仁_wansc2019_hq2019_raw_kq2019_dailyintake, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(薏苡仁_hq2019_raw_dailyintake))
```

```{r 酸枣仁 data clean, echo=FALSE}

# --------retrieve the 酸枣仁 data of wansc2109--------
t <- which(stringr::str_detect(wansc2019$CMN,"酸枣仁"))
酸枣仁 <- wansc2019[t,]
酸枣仁$DD <- as.numeric(酸枣仁$DD)
酸枣仁$days <- as.numeric(酸枣仁$days)
酸枣仁$ds <- 酸枣仁$DD*酸枣仁$days
酸枣仁$ds <- as.numeric(酸枣仁$ds)
det1<-as.data.frame(酸枣仁[,c("ID_Name","ds","CMN","days")])
#生成ID_Name为识别号的数据框 
wansc2019_intakesum<-reshape2::dcast(det1, 	
                           ID_Name ~ CMN,
                           value.var = "ds", sum)	
酸枣仁_wansc2019_intakesum<-as.vector(as.matrix(wansc2019_intakesum$`酸枣仁`))
wansc2019_dayssum<-reshape2::dcast(det1,
                      ID_Name ~  CMN,
                      value.var = "days",sum)
酸枣仁_wansc2019_dayssum<-as.vector(as.matrix(wansc2019_dayssum$`酸枣仁`))
#合并酸枣仁的消费量和days表格
wansc2019_intakemergedays <- merge(x=wansc2019_intakesum, y=wansc2019_dayssum,
                         by.x="ID_Name",
                         by.y="ID_Name"
)
options(digits = 3)
wansc2019_intakemergedays$standard <- wansc2019_intakemergedays$酸枣仁.x/wansc2019_intakemergedays$酸枣仁.y
酸枣仁_dailyintake <- as.vector(as.matrix(wansc2019_intakemergedays$standard))

# --------retrieve the 酸枣仁 data of hq2019_raw--------
酸枣仁 <- hq2019_raw[hq2019_raw$CMN =="酸枣仁",]
酸枣仁$DD <- as.numeric(酸枣仁$DD)
酸枣仁$days <- as.numeric(酸枣仁$days)
酸枣仁$total <- 酸枣仁$DD*酸枣仁$days
酸枣仁$total <- as.numeric(酸枣仁$total)
det1<-as.data.frame(酸枣仁[,c("H_Name","total","CMN","days")])
#生成H_Name为识别号的数据框
hq2019_raw_intakesum<-reshape2::dcast(det1, 	
                                  H_Name ~ CMN,
                                  value.var = "total", sum)	
酸枣仁_hq2019_raw_intakesum<-as.vector(as.matrix(hq2019_raw_intakesum$`酸枣仁`))
hq2019_raw_dayssum<-reshape2::dcast(det1,
                                H_Name ~  CMN,
                                value.var = "days",sum)
酸枣仁_hq2019_raw_dayssum<-as.vector(as.matrix(hq2019_raw_dayssum$`酸枣仁`))
#合并酸枣仁的消费量和days表格
hq2019_raw_intakemergedays <- merge(x=hq2019_raw_intakesum, y=hq2019_raw_dayssum,
                                by.x="H_Name",
                                by.y="H_Name"
)
options(digits = 3)
hq2019_raw_intakemergedays$standard <- hq2019_raw_intakemergedays$酸枣仁.x/hq2019_raw_intakemergedays$酸枣仁.y
酸枣仁_hq2019_raw_dailyintake <- as.vector(as.matrix(hq2019_raw_intakemergedays$standard))

# --------retrieve the 酸枣仁 data of kq2019--------
酸枣仁 <- kq2019[kq2019$CMN =="酸枣仁",]
酸枣仁$DD <- as.numeric(酸枣仁$DD)
酸枣仁$days <- as.numeric(酸枣仁$days)
酸枣仁$total <- 酸枣仁$DD*酸枣仁$days
酸枣仁$total <- as.numeric(酸枣仁$total)
det1<-as.data.frame(酸枣仁[,c("Name","total","CMN","days")])
#生成Name为识别号的数据框
kq2019_intakesum<-reshape2::dcast(det1, 	
                                  Name ~ CMN,
                                  value.var = "total", sum)	
酸枣仁_kq2019_intakesum<-as.vector(as.matrix(kq2019_intakesum$`酸枣仁`))
kq2019_dayssum<-reshape2::dcast(det1,
                                Name ~  CMN,
                                value.var = "days",sum)
酸枣仁_kq2019_dayssum<-as.vector(as.matrix(kq2019_dayssum$`酸枣仁`))
#合并酸枣仁的消费量和days表格
kq2019_intakemergedays <- merge(x=kq2019_intakesum, y=kq2019_dayssum,
                                by.x="Name",
                                by.y="Name"
)
options(digits = 3)
kq2019_intakemergedays$standard <- kq2019_intakemergedays$酸枣仁.x/kq2019_intakemergedays$酸枣仁.y
酸枣仁_kq2019_dailyintake <- as.vector(as.matrix(kq2019_intakemergedays$standard))

#将三个厂的数据结合
colnames(hq2019_raw_intakemergedays) <- c("Name","intakesum","days","standard")
colnames(wansc2019_intakemergedays) <- c("Name","intakesum","days","standard")
colnames(kq2019_intakemergedays) <- c("Name","intakesum","days","standard")
hq2019_raw_kq2019_intakemergedays <- rbind(hq2019_raw_intakemergedays,kq2019_intakemergedays)
wansc2019_hq2019_raw_kq2019_intakemergedays <- rbind(hq2019_raw_kq2019_intakemergedays,wansc2019_intakemergedays)
colnames(wansc2019_hq2019_raw_kq2019_intakemergedays) <- c("Name","intakesum","days","standard")
write.table(wansc2019_hq2019_raw_kq2019_intakemergedays,file="E:\\R export\\Personal intake disturbution of 酸枣仁 .csv",row.names = F,col.names = T,sep=",")
```


<center>
```{r 酸枣仁 quantile calculate, echo=FALSE}
# Calculate the 酸枣仁 quantile of annual_intake
options(digits=4)
酸枣仁_wansc2019_hq2019_raw_kq2019_intakesum <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$intakesum))
酸枣仁_annual_intake<-c(quantile(酸枣仁_wansc2019_hq2019_raw_kq2019_intakesum, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(酸枣仁_wansc2019_hq2019_raw_kq2019_intakesum))
# Calculate the 酸枣仁 quantile of intake_days
酸枣仁_wansc2019_hq2019_raw_kq2019_dayssum <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$days))
酸枣仁_intake_days <- c(quantile(酸枣仁_wansc2019_hq2019_raw_kq2019_dayssum, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(酸枣仁_wansc2019_hq2019_raw_kq2019_dayssum))
# Calculate the 酸枣仁 quantile of daily_intake
酸枣仁_wansc2019_hq2019_raw_kq2019_dailyintake <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$standard))
酸枣仁_daily_intake <- c(quantile(酸枣仁_wansc2019_hq2019_raw_kq2019_dailyintake, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(酸枣仁_hq2019_raw_dailyintake))
```

```{r 白术 data clean, echo=FALSE}

# --------retrieve the 白术 data of wansc2109--------
t <- which(stringr::str_detect(wansc2019$CMN,"白术"))
白术 <- wansc2019[t,]
白术$DD <- as.numeric(白术$DD)
白术$days <- as.numeric(白术$days)
白术$ds <- 白术$DD*白术$days
白术$ds <- as.numeric(白术$ds)
det1<-as.data.frame(白术[,c("ID_Name","ds","CMN","days")])
#生成ID_Name为识别号的数据框 
wansc2019_intakesum<-reshape2::dcast(det1, 	
                           ID_Name ~ CMN,
                           value.var = "ds", sum)	
白术_wansc2019_intakesum<-as.vector(as.matrix(wansc2019_intakesum$`白术`))
wansc2019_dayssum<-reshape2::dcast(det1,
                      ID_Name ~  CMN,
                      value.var = "days",sum)
白术_wansc2019_dayssum<-as.vector(as.matrix(wansc2019_dayssum$`白术`))
#合并白术的消费量和days表格
wansc2019_intakemergedays <- merge(x=wansc2019_intakesum, y=wansc2019_dayssum,
                         by.x="ID_Name",
                         by.y="ID_Name"
)
options(digits = 3)
wansc2019_intakemergedays$standard <- wansc2019_intakemergedays$白术.x/wansc2019_intakemergedays$白术.y
白术_dailyintake <- as.vector(as.matrix(wansc2019_intakemergedays$standard))

# --------retrieve the 白术 data of hq2019_raw--------
白术 <- hq2019_raw[hq2019_raw$CMN =="白术",]
白术$DD <- as.numeric(白术$DD)
白术$days <- as.numeric(白术$days)
白术$total <- 白术$DD*白术$days
白术$total <- as.numeric(白术$total)
det1<-as.data.frame(白术[,c("H_Name","total","CMN","days")])
#生成H_Name为识别号的数据框
hq2019_raw_intakesum<-reshape2::dcast(det1, 	
                                  H_Name ~ CMN,
                                  value.var = "total", sum)	
白术_hq2019_raw_intakesum<-as.vector(as.matrix(hq2019_raw_intakesum$`白术`))
hq2019_raw_dayssum<-reshape2::dcast(det1,
                                H_Name ~  CMN,
                                value.var = "days",sum)
白术_hq2019_raw_dayssum<-as.vector(as.matrix(hq2019_raw_dayssum$`白术`))
#合并白术的消费量和days表格
hq2019_raw_intakemergedays <- merge(x=hq2019_raw_intakesum, y=hq2019_raw_dayssum,
                                by.x="H_Name",
                                by.y="H_Name"
)
options(digits = 3)
hq2019_raw_intakemergedays$standard <- hq2019_raw_intakemergedays$白术.x/hq2019_raw_intakemergedays$白术.y
白术_hq2019_raw_dailyintake <- as.vector(as.matrix(hq2019_raw_intakemergedays$standard))

# --------retrieve the 白术 data of kq2019--------
白术 <- kq2019[kq2019$CMN =="白术",]
白术$DD <- as.numeric(白术$DD)
白术$days <- as.numeric(白术$days)
白术$total <- 白术$DD*白术$days
白术$total <- as.numeric(白术$total)
det1<-as.data.frame(白术[,c("Name","total","CMN","days")])
#生成Name为识别号的数据框
kq2019_intakesum<-reshape2::dcast(det1, 	
                                  Name ~ CMN,
                                  value.var = "total", sum)	
白术_kq2019_intakesum<-as.vector(as.matrix(kq2019_intakesum$`白术`))
kq2019_dayssum<-reshape2::dcast(det1,
                                Name ~  CMN,
                                value.var = "days",sum)
白术_kq2019_dayssum<-as.vector(as.matrix(kq2019_dayssum$`白术`))
#合并白术的消费量和days表格
kq2019_intakemergedays <- merge(x=kq2019_intakesum, y=kq2019_dayssum,
                                by.x="Name",
                                by.y="Name"
)
options(digits = 3)
kq2019_intakemergedays$standard <- kq2019_intakemergedays$白术.x/kq2019_intakemergedays$白术.y
白术_kq2019_dailyintake <- as.vector(as.matrix(kq2019_intakemergedays$standard))

#将三个厂的数据结合
colnames(hq2019_raw_intakemergedays) <- c("Name","intakesum","days","standard")
colnames(wansc2019_intakemergedays) <- c("Name","intakesum","days","standard")
colnames(kq2019_intakemergedays) <- c("Name","intakesum","days","standard")
hq2019_raw_kq2019_intakemergedays <- rbind(hq2019_raw_intakemergedays,kq2019_intakemergedays)
wansc2019_hq2019_raw_kq2019_intakemergedays <- rbind(hq2019_raw_kq2019_intakemergedays,wansc2019_intakemergedays)
colnames(wansc2019_hq2019_raw_kq2019_intakemergedays) <- c("Name","intakesum","days","standard")
write.table(wansc2019_hq2019_raw_kq2019_intakemergedays,file="E:\\R export\\Personal intake disturbution of 白术 .csv",row.names = F,col.names = T,sep=",")
```


<center>
```{r 白术 quantile calculate, echo=FALSE}
# Calculate the 白术 quantile of annual_intake
options(digits=4)
白术_wansc2019_hq2019_raw_kq2019_intakesum <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$intakesum))
白术_annual_intake<-c(quantile(白术_wansc2019_hq2019_raw_kq2019_intakesum, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(白术_wansc2019_hq2019_raw_kq2019_intakesum))
# Calculate the 白术 quantile of intake_days
白术_wansc2019_hq2019_raw_kq2019_dayssum <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$days))
白术_intake_days <- c(quantile(白术_wansc2019_hq2019_raw_kq2019_dayssum, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(白术_wansc2019_hq2019_raw_kq2019_dayssum))
# Calculate the 白术 quantile of daily_intake
白术_wansc2019_hq2019_raw_kq2019_dailyintake <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$standard))
白术_daily_intake <- c(quantile(白术_wansc2019_hq2019_raw_kq2019_dailyintake, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(白术_hq2019_raw_dailyintake))
```


```{r 三七 data clean, echo=FALSE}

# --------retrieve the 三七 data of wansc2109--------
t <- which(stringr::str_detect(wansc2019$CMN,"三七"))
三七 <- wansc2019[t,]
三七$DD <- as.numeric(三七$DD)
三七$days <- as.numeric(三七$days)
三七$ds <- 三七$DD*三七$days
三七$ds <- as.numeric(三七$ds)
det1<-as.data.frame(三七[,c("ID_Name","ds","CMN","days")])
#生成ID_Name为识别号的数据框 
wansc2019_intakesum<-reshape2::dcast(det1, 	
                           ID_Name ~ CMN,
                           value.var = "ds", sum)	
三七_wansc2019_intakesum<-as.vector(as.matrix(wansc2019_intakesum$`三七`))
wansc2019_dayssum<-reshape2::dcast(det1,
                      ID_Name ~  CMN,
                      value.var = "days",sum)
三七_wansc2019_dayssum<-as.vector(as.matrix(wansc2019_dayssum$`三七`))
#合并三七的消费量和days表格
wansc2019_intakemergedays <- merge(x=wansc2019_intakesum, y=wansc2019_dayssum,
                         by.x="ID_Name",
                         by.y="ID_Name"
)
options(digits = 3)
wansc2019_intakemergedays$standard <- wansc2019_intakemergedays$三七.x/wansc2019_intakemergedays$三七.y
三七_dailyintake <- as.vector(as.matrix(wansc2019_intakemergedays$standard))

# --------retrieve the 三七 data of hq2019_raw--------
三七 <- hq2019_raw[hq2019_raw$CMN =="三七",]
三七$DD <- as.numeric(三七$DD)
三七$days <- as.numeric(三七$days)
三七$total <- 三七$DD*三七$days
三七$total <- as.numeric(三七$total)
det1<-as.data.frame(三七[,c("H_Name","total","CMN","days")])
#生成H_Name为识别号的数据框
hq2019_raw_intakesum<-reshape2::dcast(det1, 	
                                  H_Name ~ CMN,
                                  value.var = "total", sum)	
三七_hq2019_raw_intakesum<-as.vector(as.matrix(hq2019_raw_intakesum$`三七`))
hq2019_raw_dayssum<-reshape2::dcast(det1,
                                H_Name ~  CMN,
                                value.var = "days",sum)
三七_hq2019_raw_dayssum<-as.vector(as.matrix(hq2019_raw_dayssum$`三七`))
#合并三七的消费量和days表格
hq2019_raw_intakemergedays <- merge(x=hq2019_raw_intakesum, y=hq2019_raw_dayssum,
                                by.x="H_Name",
                                by.y="H_Name"
)
options(digits = 3)
hq2019_raw_intakemergedays$standard <- hq2019_raw_intakemergedays$三七.x/hq2019_raw_intakemergedays$三七.y
三七_hq2019_raw_dailyintake <- as.vector(as.matrix(hq2019_raw_intakemergedays$standard))

# --------retrieve the 三七 data of kq2019--------
三七 <- kq2019[kq2019$CMN =="三七",]
三七$DD <- as.numeric(三七$DD)
三七$days <- as.numeric(三七$days)
三七$total <- 三七$DD*三七$days
三七$total <- as.numeric(三七$total)
det1<-as.data.frame(三七[,c("Name","total","CMN","days")])
#生成Name为识别号的数据框
kq2019_intakesum<-reshape2::dcast(det1, 	
                                  Name ~ CMN,
                                  value.var = "total", sum)	
三七_kq2019_intakesum<-as.vector(as.matrix(kq2019_intakesum$`三七`))
kq2019_dayssum<-reshape2::dcast(det1,
                                Name ~  CMN,
                                value.var = "days",sum)
三七_kq2019_dayssum<-as.vector(as.matrix(kq2019_dayssum$`三七`))
#合并三七的消费量和days表格
kq2019_intakemergedays <- merge(x=kq2019_intakesum, y=kq2019_dayssum,
                                by.x="Name",
                                by.y="Name"
)
options(digits = 3)
kq2019_intakemergedays$standard <- kq2019_intakemergedays$三七.x/kq2019_intakemergedays$三七.y
三七_kq2019_dailyintake <- as.vector(as.matrix(kq2019_intakemergedays$standard))

#将三个厂的数据结合
colnames(hq2019_raw_intakemergedays) <- c("Name","intakesum","days","standard")
colnames(wansc2019_intakemergedays) <- c("Name","intakesum","days","standard")
colnames(kq2019_intakemergedays) <- c("Name","intakesum","days","standard")
hq2019_raw_kq2019_intakemergedays <- rbind(hq2019_raw_intakemergedays,kq2019_intakemergedays)
wansc2019_hq2019_raw_kq2019_intakemergedays <- rbind(hq2019_raw_kq2019_intakemergedays,wansc2019_intakemergedays)
colnames(wansc2019_hq2019_raw_kq2019_intakemergedays) <- c("Name","intakesum","days","standard")
write.table(wansc2019_hq2019_raw_kq2019_intakemergedays,file="E:\\R export\\Personal intake disturbution of 三七 .csv",row.names = F,col.names = T,sep=",")
```


<center>
```{r 三七 quantile calculate, echo=FALSE}
# Calculate the 三七 quantile of annual_intake
options(digits=4)
三七_wansc2019_hq2019_raw_kq2019_intakesum <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$intakesum))
三七_annual_intake<-c(quantile(三七_wansc2019_hq2019_raw_kq2019_intakesum, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(三七_wansc2019_hq2019_raw_kq2019_intakesum))
# Calculate the 三七 quantile of intake_days
三七_wansc2019_hq2019_raw_kq2019_dayssum <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$days))
三七_intake_days <- c(quantile(三七_wansc2019_hq2019_raw_kq2019_dayssum, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(三七_wansc2019_hq2019_raw_kq2019_dayssum))
# Calculate the 三七 quantile of daily_intake
三七_wansc2019_hq2019_raw_kq2019_dailyintake <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$standard))
三七_daily_intake <- c(quantile(三七_wansc2019_hq2019_raw_kq2019_dailyintake, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(三七_hq2019_raw_dailyintake))
```

```{r 丹参 data clean, echo=FALSE}

# --------retrieve the 丹参 data of wansc2109--------
t <- which(stringr::str_detect(wansc2019$CMN,"丹参"))
丹参 <- wansc2019[t,]
丹参$DD <- as.numeric(丹参$DD)
丹参$days <- as.numeric(丹参$days)
丹参$ds <- 丹参$DD*丹参$days
丹参$ds <- as.numeric(丹参$ds)
det1<-as.data.frame(丹参[,c("ID_Name","ds","CMN","days")])
#生成ID_Name为识别号的数据框 
wansc2019_intakesum<-reshape2::dcast(det1, 	
                           ID_Name ~ CMN,
                           value.var = "ds", sum)	
丹参_wansc2019_intakesum<-as.vector(as.matrix(wansc2019_intakesum$`丹参`))
wansc2019_dayssum<-reshape2::dcast(det1,
                      ID_Name ~  CMN,
                      value.var = "days",sum)
丹参_wansc2019_dayssum<-as.vector(as.matrix(wansc2019_dayssum$`丹参`))
#合并丹参的消费量和days表格
wansc2019_intakemergedays <- merge(x=wansc2019_intakesum, y=wansc2019_dayssum,
                         by.x="ID_Name",
                         by.y="ID_Name"
)
options(digits = 3)
wansc2019_intakemergedays$standard <- wansc2019_intakemergedays$丹参.x/wansc2019_intakemergedays$丹参.y
丹参_dailyintake <- as.vector(as.matrix(wansc2019_intakemergedays$standard))

# --------retrieve the 丹参 data of hq2019_raw--------
丹参 <- hq2019_raw[hq2019_raw$CMN =="丹参",]
丹参$DD <- as.numeric(丹参$DD)
丹参$days <- as.numeric(丹参$days)
丹参$total <- 丹参$DD*丹参$days
丹参$total <- as.numeric(丹参$total)
det1<-as.data.frame(丹参[,c("H_Name","total","CMN","days")])
#生成H_Name为识别号的数据框
hq2019_raw_intakesum<-reshape2::dcast(det1, 	
                                  H_Name ~ CMN,
                                  value.var = "total", sum)	
丹参_hq2019_raw_intakesum<-as.vector(as.matrix(hq2019_raw_intakesum$`丹参`))
hq2019_raw_dayssum<-reshape2::dcast(det1,
                                H_Name ~  CMN,
                                value.var = "days",sum)
丹参_hq2019_raw_dayssum<-as.vector(as.matrix(hq2019_raw_dayssum$`丹参`))
#合并丹参的消费量和days表格
hq2019_raw_intakemergedays <- merge(x=hq2019_raw_intakesum, y=hq2019_raw_dayssum,
                                by.x="H_Name",
                                by.y="H_Name"
)
options(digits = 3)
hq2019_raw_intakemergedays$standard <- hq2019_raw_intakemergedays$丹参.x/hq2019_raw_intakemergedays$丹参.y
丹参_hq2019_raw_dailyintake <- as.vector(as.matrix(hq2019_raw_intakemergedays$standard))

# --------retrieve the 丹参 data of kq2019--------
丹参 <- kq2019[kq2019$CMN =="丹参",]
丹参$DD <- as.numeric(丹参$DD)
丹参$days <- as.numeric(丹参$days)
丹参$total <- 丹参$DD*丹参$days
丹参$total <- as.numeric(丹参$total)
det1<-as.data.frame(丹参[,c("Name","total","CMN","days")])
#生成Name为识别号的数据框
kq2019_intakesum<-reshape2::dcast(det1, 	
                                  Name ~ CMN,
                                  value.var = "total", sum)	
丹参_kq2019_intakesum<-as.vector(as.matrix(kq2019_intakesum$`丹参`))
kq2019_dayssum<-reshape2::dcast(det1,
                                Name ~  CMN,
                                value.var = "days",sum)
丹参_kq2019_dayssum<-as.vector(as.matrix(kq2019_dayssum$`丹参`))
#合并丹参的消费量和days表格
kq2019_intakemergedays <- merge(x=kq2019_intakesum, y=kq2019_dayssum,
                                by.x="Name",
                                by.y="Name"
)
options(digits = 3)
kq2019_intakemergedays$standard <- kq2019_intakemergedays$丹参.x/kq2019_intakemergedays$丹参.y
丹参_kq2019_dailyintake <- as.vector(as.matrix(kq2019_intakemergedays$standard))

#将三个厂的数据结合
colnames(hq2019_raw_intakemergedays) <- c("Name","intakesum","days","standard")
colnames(wansc2019_intakemergedays) <- c("Name","intakesum","days","standard")
colnames(kq2019_intakemergedays) <- c("Name","intakesum","days","standard")
hq2019_raw_kq2019_intakemergedays <- rbind(hq2019_raw_intakemergedays,kq2019_intakemergedays)
wansc2019_hq2019_raw_kq2019_intakemergedays <- rbind(hq2019_raw_kq2019_intakemergedays,wansc2019_intakemergedays)
colnames(wansc2019_hq2019_raw_kq2019_intakemergedays) <- c("Name","intakesum","days","standard")
write.table(wansc2019_hq2019_raw_kq2019_intakemergedays,file="E:\\R export\\Personal intake disturbution of 丹参 .csv",row.names = F,col.names = T,sep=",")
```


<center>
```{r 丹参 quantile calculate, echo=FALSE}
# Calculate the 丹参 quantile of annual_intake
options(digits=4)
丹参_wansc2019_hq2019_raw_kq2019_intakesum <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$intakesum))
丹参_annual_intake<-c(quantile(丹参_wansc2019_hq2019_raw_kq2019_intakesum, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(丹参_wansc2019_hq2019_raw_kq2019_intakesum))
# Calculate the 丹参 quantile of intake_days
丹参_wansc2019_hq2019_raw_kq2019_dayssum <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$days))
丹参_intake_days <- c(quantile(丹参_wansc2019_hq2019_raw_kq2019_dayssum, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(丹参_wansc2019_hq2019_raw_kq2019_dayssum))
# Calculate the 丹参 quantile of daily_intake
丹参_wansc2019_hq2019_raw_kq2019_dailyintake <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$standard))
丹参_daily_intake <- c(quantile(丹参_wansc2019_hq2019_raw_kq2019_dailyintake, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(丹参_hq2019_raw_dailyintake))
```


```{r 人参 data clean, echo=FALSE}

# --------retrieve the 人参 data of wansc2109--------
t <- which(stringr::str_detect(wansc2019$CMN,"人参"))
人参 <- wansc2019[t,]
人参$DD <- as.numeric(人参$DD)
人参$days <- as.numeric(人参$days)
人参$ds <- 人参$DD*人参$days
人参$ds <- as.numeric(人参$ds)
det1<-as.data.frame(人参[,c("ID_Name","ds","CMN","days")])
#生成ID_Name为识别号的数据框 
wansc2019_intakesum<-reshape2::dcast(det1, 	
                           ID_Name ~ CMN,
                           value.var = "ds", sum)	
人参_wansc2019_intakesum<-as.vector(as.matrix(wansc2019_intakesum$`人参`))
wansc2019_dayssum<-reshape2::dcast(det1,
                      ID_Name ~  CMN,
                      value.var = "days",sum)
人参_wansc2019_dayssum<-as.vector(as.matrix(wansc2019_dayssum$`人参`))
#合并人参的消费量和days表格
wansc2019_intakemergedays <- merge(x=wansc2019_intakesum, y=wansc2019_dayssum,
                         by.x="ID_Name",
                         by.y="ID_Name"
)
options(digits = 3)
wansc2019_intakemergedays$standard <- wansc2019_intakemergedays$人参.x/wansc2019_intakemergedays$人参.y
人参_dailyintake <- as.vector(as.matrix(wansc2019_intakemergedays$standard))

# --------retrieve the 人参 data of hq2019_raw--------
人参 <- hq2019_raw[hq2019_raw$CMN =="人参",]
人参$DD <- as.numeric(人参$DD)
人参$days <- as.numeric(人参$days)
人参$total <- 人参$DD*人参$days
人参$total <- as.numeric(人参$total)
det1<-as.data.frame(人参[,c("H_Name","total","CMN","days")])
#生成H_Name为识别号的数据框
hq2019_raw_intakesum<-reshape2::dcast(det1, 	
                                  H_Name ~ CMN,
                                  value.var = "total", sum)	
人参_hq2019_raw_intakesum<-as.vector(as.matrix(hq2019_raw_intakesum$`人参`))
hq2019_raw_dayssum<-reshape2::dcast(det1,
                                H_Name ~  CMN,
                                value.var = "days",sum)
人参_hq2019_raw_dayssum<-as.vector(as.matrix(hq2019_raw_dayssum$`人参`))
#合并人参的消费量和days表格
hq2019_raw_intakemergedays <- merge(x=hq2019_raw_intakesum, y=hq2019_raw_dayssum,
                                by.x="H_Name",
                                by.y="H_Name"
)
options(digits = 3)
hq2019_raw_intakemergedays$standard <- hq2019_raw_intakemergedays$人参.x/hq2019_raw_intakemergedays$人参.y
人参_hq2019_raw_dailyintake <- as.vector(as.matrix(hq2019_raw_intakemergedays$standard))

# --------retrieve the 人参 data of kq2019--------
人参 <- kq2019[kq2019$CMN =="人参",]
人参$DD <- as.numeric(人参$DD)
人参$days <- as.numeric(人参$days)
人参$total <- 人参$DD*人参$days
人参$total <- as.numeric(人参$total)
det1<-as.data.frame(人参[,c("Name","total","CMN","days")])
#生成Name为识别号的数据框
kq2019_intakesum<-reshape2::dcast(det1, 	
                                  Name ~ CMN,
                                  value.var = "total", sum)	
人参_kq2019_intakesum<-as.vector(as.matrix(kq2019_intakesum$`人参`))
kq2019_dayssum<-reshape2::dcast(det1,
                                Name ~  CMN,
                                value.var = "days",sum)
人参_kq2019_dayssum<-as.vector(as.matrix(kq2019_dayssum$`人参`))
#合并人参的消费量和days表格
kq2019_intakemergedays <- merge(x=kq2019_intakesum, y=kq2019_dayssum,
                                by.x="Name",
                                by.y="Name"
)
options(digits = 3)
kq2019_intakemergedays$standard <- kq2019_intakemergedays$人参.x/kq2019_intakemergedays$人参.y
人参_kq2019_dailyintake <- as.vector(as.matrix(kq2019_intakemergedays$standard))

#将三个厂的数据结合
colnames(hq2019_raw_intakemergedays) <- c("Name","intakesum","days","standard")
colnames(wansc2019_intakemergedays) <- c("Name","intakesum","days","standard")
colnames(kq2019_intakemergedays) <- c("Name","intakesum","days","standard")
hq2019_raw_kq2019_intakemergedays <- rbind(hq2019_raw_intakemergedays,kq2019_intakemergedays)
wansc2019_hq2019_raw_kq2019_intakemergedays <- rbind(hq2019_raw_kq2019_intakemergedays,wansc2019_intakemergedays)
colnames(wansc2019_hq2019_raw_kq2019_intakemergedays) <- c("Name","intakesum","days","standard")
write.table(wansc2019_hq2019_raw_kq2019_intakemergedays,file="E:\\R export\\Personal intake disturbution of 人参 .csv",row.names = F,col.names = T,sep=",")
```


<center>
```{r 人参 quantile calculate, echo=FALSE}
# Calculate the 人参 quantile of annual_intake
options(digits=4)
人参_wansc2019_hq2019_raw_kq2019_intakesum <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$intakesum))
人参_annual_intake<-c(quantile(人参_wansc2019_hq2019_raw_kq2019_intakesum, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(人参_wansc2019_hq2019_raw_kq2019_intakesum))
# Calculate the 人参 quantile of intake_days
人参_wansc2019_hq2019_raw_kq2019_dayssum <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$days))
人参_intake_days <- c(quantile(人参_wansc2019_hq2019_raw_kq2019_dayssum, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(人参_wansc2019_hq2019_raw_kq2019_dayssum))
# Calculate the 人参 quantile of daily_intake
人参_wansc2019_hq2019_raw_kq2019_dailyintake <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$standard))
人参_daily_intake <- c(quantile(人参_wansc2019_hq2019_raw_kq2019_dailyintake, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(人参_hq2019_raw_dailyintake))
```


```{r 枸杞 data clean, echo=FALSE}

# --------retrieve the 枸杞 data of wansc2109--------
t <- which(stringr::str_detect(wansc2019$CMN,"枸杞"))
枸杞 <- wansc2019[t,]
枸杞$DD <- as.numeric(枸杞$DD)
枸杞$days <- as.numeric(枸杞$days)
枸杞$ds <- 枸杞$DD*枸杞$days
枸杞$ds <- as.numeric(枸杞$ds)
det1<-as.data.frame(枸杞[,c("ID_Name","ds","CMN","days")])
#生成ID_Name为识别号的数据框 
wansc2019_intakesum<-reshape2::dcast(det1, 	
                           ID_Name ~ CMN,
                           value.var = "ds", sum)	
枸杞_wansc2019_intakesum<-as.vector(as.matrix(wansc2019_intakesum$`枸杞`))
wansc2019_dayssum<-reshape2::dcast(det1,
                      ID_Name ~  CMN,
                      value.var = "days",sum)
枸杞_wansc2019_dayssum<-as.vector(as.matrix(wansc2019_dayssum$`枸杞`))
#合并枸杞的消费量和days表格
wansc2019_intakemergedays <- merge(x=wansc2019_intakesum, y=wansc2019_dayssum,
                         by.x="ID_Name",
                         by.y="ID_Name"
)
options(digits = 3)
wansc2019_intakemergedays$standard <- wansc2019_intakemergedays$枸杞.x/wansc2019_intakemergedays$枸杞.y
枸杞_dailyintake <- as.vector(as.matrix(wansc2019_intakemergedays$standard))

# --------retrieve the 枸杞 data of hq2019_raw--------
枸杞 <- hq2019_raw[hq2019_raw$CMN =="枸杞",]
枸杞$DD <- as.numeric(枸杞$DD)
枸杞$days <- as.numeric(枸杞$days)
枸杞$total <- 枸杞$DD*枸杞$days
枸杞$total <- as.numeric(枸杞$total)
det1<-as.data.frame(枸杞[,c("H_Name","total","CMN","days")])
#生成H_Name为识别号的数据框
hq2019_raw_intakesum<-reshape2::dcast(det1, 	
                                  H_Name ~ CMN,
                                  value.var = "total", sum)	
枸杞_hq2019_raw_intakesum<-as.vector(as.matrix(hq2019_raw_intakesum$`枸杞`))
hq2019_raw_dayssum<-reshape2::dcast(det1,
                                H_Name ~  CMN,
                                value.var = "days",sum)
枸杞_hq2019_raw_dayssum<-as.vector(as.matrix(hq2019_raw_dayssum$`枸杞`))
#合并枸杞的消费量和days表格
hq2019_raw_intakemergedays <- merge(x=hq2019_raw_intakesum, y=hq2019_raw_dayssum,
                                by.x="H_Name",
                                by.y="H_Name"
)
options(digits = 3)
hq2019_raw_intakemergedays$standard <- hq2019_raw_intakemergedays$枸杞.x/hq2019_raw_intakemergedays$枸杞.y
枸杞_hq2019_raw_dailyintake <- as.vector(as.matrix(hq2019_raw_intakemergedays$standard))

# --------retrieve the 枸杞 data of kq2019--------
枸杞 <- kq2019[kq2019$CMN =="枸杞",]
枸杞$DD <- as.numeric(枸杞$DD)
枸杞$days <- as.numeric(枸杞$days)
枸杞$total <- 枸杞$DD*枸杞$days
枸杞$total <- as.numeric(枸杞$total)
det1<-as.data.frame(枸杞[,c("Name","total","CMN","days")])
#生成Name为识别号的数据框
kq2019_intakesum<-reshape2::dcast(det1, 	
                                  Name ~ CMN,
                                  value.var = "total", sum)	
枸杞_kq2019_intakesum<-as.vector(as.matrix(kq2019_intakesum$`枸杞`))
kq2019_dayssum<-reshape2::dcast(det1,
                                Name ~  CMN,
                                value.var = "days",sum)
枸杞_kq2019_dayssum<-as.vector(as.matrix(kq2019_dayssum$`枸杞`))
#合并枸杞的消费量和days表格
kq2019_intakemergedays <- merge(x=kq2019_intakesum, y=kq2019_dayssum,
                                by.x="Name",
                                by.y="Name"
)
options(digits = 3)
kq2019_intakemergedays$standard <- kq2019_intakemergedays$枸杞.x/kq2019_intakemergedays$枸杞.y
枸杞_kq2019_dailyintake <- as.vector(as.matrix(kq2019_intakemergedays$standard))

#将三个厂的数据结合
colnames(hq2019_raw_intakemergedays) <- c("Name","intakesum","days","standard")
colnames(wansc2019_intakemergedays) <- c("Name","intakesum","days","standard")
colnames(kq2019_intakemergedays) <- c("Name","intakesum","days","standard")
hq2019_raw_kq2019_intakemergedays <- rbind(hq2019_raw_intakemergedays,kq2019_intakemergedays)
wansc2019_hq2019_raw_kq2019_intakemergedays <- rbind(hq2019_raw_kq2019_intakemergedays,wansc2019_intakemergedays)
colnames(wansc2019_hq2019_raw_kq2019_intakemergedays) <- c("Name","intakesum","days","standard")
write.table(wansc2019_hq2019_raw_kq2019_intakemergedays,file="E:\\R export\\Personal intake disturbution of 枸杞 .csv",row.names = F,col.names = T,sep=",")
```


<center>
```{r 枸杞 quantile calculate, echo=FALSE}
# Calculate the 枸杞 quantile of annual_intake
options(digits=4)
枸杞_wansc2019_hq2019_raw_kq2019_intakesum <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$intakesum))
枸杞_annual_intake<-c(quantile(枸杞_wansc2019_hq2019_raw_kq2019_intakesum, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(枸杞_wansc2019_hq2019_raw_kq2019_intakesum))
# Calculate the 枸杞 quantile of intake_days
枸杞_wansc2019_hq2019_raw_kq2019_dayssum <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$days))
枸杞_intake_days <- c(quantile(枸杞_wansc2019_hq2019_raw_kq2019_dayssum, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(枸杞_wansc2019_hq2019_raw_kq2019_dayssum))
# Calculate the 枸杞 quantile of daily_intake
枸杞_wansc2019_hq2019_raw_kq2019_dailyintake <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$standard))
枸杞_daily_intake <- c(quantile(枸杞_wansc2019_hq2019_raw_kq2019_dailyintake, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(枸杞_hq2019_raw_dailyintake))
```



```{r 金银花 data clean, echo=FALSE}

# --------retrieve the 金银花 data of wansc2109--------
t <- which(stringr::str_detect(wansc2019$CMN,"金银花"))
金银花 <- wansc2019[t,]
金银花$DD <- as.numeric(金银花$DD)
金银花$days <- as.numeric(金银花$days)
金银花$ds <- 金银花$DD*金银花$days
金银花$ds <- as.numeric(金银花$ds)
det1<-as.data.frame(金银花[,c("ID_Name","ds","CMN","days")])
#生成ID_Name为识别号的数据框 
wansc2019_intakesum<-reshape2::dcast(det1, 	
                           ID_Name ~ CMN,
                           value.var = "ds", sum)	
金银花_wansc2019_intakesum<-as.vector(as.matrix(wansc2019_intakesum$`金银花`))
wansc2019_dayssum<-reshape2::dcast(det1,
                      ID_Name ~  CMN,
                      value.var = "days",sum)
金银花_wansc2019_dayssum<-as.vector(as.matrix(wansc2019_dayssum$`金银花`))
#合并金银花的消费量和days表格
wansc2019_intakemergedays <- merge(x=wansc2019_intakesum, y=wansc2019_dayssum,
                         by.x="ID_Name",
                         by.y="ID_Name"
)
options(digits = 3)
wansc2019_intakemergedays$standard <- wansc2019_intakemergedays$金银花.x/wansc2019_intakemergedays$金银花.y
金银花_dailyintake <- as.vector(as.matrix(wansc2019_intakemergedays$standard))

# --------retrieve the 金银花 data of hq2019_raw--------
金银花 <- hq2019_raw[hq2019_raw$CMN =="金银花",]
金银花$DD <- as.numeric(金银花$DD)
金银花$days <- as.numeric(金银花$days)
金银花$total <- 金银花$DD*金银花$days
金银花$total <- as.numeric(金银花$total)
det1<-as.data.frame(金银花[,c("H_Name","total","CMN","days")])
#生成H_Name为识别号的数据框
hq2019_raw_intakesum<-reshape2::dcast(det1, 	
                                  H_Name ~ CMN,
                                  value.var = "total", sum)	
金银花_hq2019_raw_intakesum<-as.vector(as.matrix(hq2019_raw_intakesum$`金银花`))
hq2019_raw_dayssum<-reshape2::dcast(det1,
                                H_Name ~  CMN,
                                value.var = "days",sum)
金银花_hq2019_raw_dayssum<-as.vector(as.matrix(hq2019_raw_dayssum$`金银花`))
#合并金银花的消费量和days表格
hq2019_raw_intakemergedays <- merge(x=hq2019_raw_intakesum, y=hq2019_raw_dayssum,
                                by.x="H_Name",
                                by.y="H_Name"
)
options(digits = 3)
hq2019_raw_intakemergedays$standard <- hq2019_raw_intakemergedays$金银花.x/hq2019_raw_intakemergedays$金银花.y
金银花_hq2019_raw_dailyintake <- as.vector(as.matrix(hq2019_raw_intakemergedays$standard))

# --------retrieve the 金银花 data of kq2019--------
金银花 <- kq2019[kq2019$CMN =="金银花",]
金银花$DD <- as.numeric(金银花$DD)
金银花$days <- as.numeric(金银花$days)
金银花$total <- 金银花$DD*金银花$days
金银花$total <- as.numeric(金银花$total)
det1<-as.data.frame(金银花[,c("Name","total","CMN","days")])
#生成Name为识别号的数据框
kq2019_intakesum<-reshape2::dcast(det1, 	
                                  Name ~ CMN,
                                  value.var = "total", sum)	
金银花_kq2019_intakesum<-as.vector(as.matrix(kq2019_intakesum$`金银花`))
kq2019_dayssum<-reshape2::dcast(det1,
                                Name ~  CMN,
                                value.var = "days",sum)
金银花_kq2019_dayssum<-as.vector(as.matrix(kq2019_dayssum$`金银花`))
#合并金银花的消费量和days表格
kq2019_intakemergedays <- merge(x=kq2019_intakesum, y=kq2019_dayssum,
                                by.x="Name",
                                by.y="Name"
)
options(digits = 3)
kq2019_intakemergedays$standard <- kq2019_intakemergedays$金银花.x/kq2019_intakemergedays$金银花.y
金银花_kq2019_dailyintake <- as.vector(as.matrix(kq2019_intakemergedays$standard))

#将三个厂的数据结合
colnames(hq2019_raw_intakemergedays) <- c("Name","intakesum","days","standard")
colnames(wansc2019_intakemergedays) <- c("Name","intakesum","days","standard")
colnames(kq2019_intakemergedays) <- c("Name","intakesum","days","standard")
hq2019_raw_kq2019_intakemergedays <- rbind(hq2019_raw_intakemergedays,kq2019_intakemergedays)
wansc2019_hq2019_raw_kq2019_intakemergedays <- rbind(hq2019_raw_kq2019_intakemergedays,wansc2019_intakemergedays)
colnames(wansc2019_hq2019_raw_kq2019_intakemergedays) <- c("Name","intakesum","days","standard")
write.table(wansc2019_hq2019_raw_kq2019_intakemergedays,file="E:\\R export\\Personal intake disturbution of 金银花 .csv",row.names = F,col.names = T,sep=",")
```


<center>
```{r 金银花 quantile calculate, echo=FALSE}
# Calculate the 金银花 quantile of annual_intake
options(digits=4)
金银花_wansc2019_hq2019_raw_kq2019_intakesum <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$intakesum))
金银花_annual_intake<-c(quantile(金银花_wansc2019_hq2019_raw_kq2019_intakesum, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(金银花_wansc2019_hq2019_raw_kq2019_intakesum))
# Calculate the 金银花 quantile of intake_days
金银花_wansc2019_hq2019_raw_kq2019_dayssum <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$days))
金银花_intake_days <- c(quantile(金银花_wansc2019_hq2019_raw_kq2019_dayssum, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(金银花_wansc2019_hq2019_raw_kq2019_dayssum))
# Calculate the 金银花 quantile of daily_intake
金银花_wansc2019_hq2019_raw_kq2019_dailyintake <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$standard))
金银花_daily_intake <- c(quantile(金银花_wansc2019_hq2019_raw_kq2019_dailyintake, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(金银花_hq2019_raw_dailyintake))
```



```{r 麦冬 data clean, echo=FALSE}

# --------retrieve the 麦冬 data of wansc2109--------
t <- which(stringr::str_detect(wansc2019$CMN,"麦冬"))
麦冬 <- wansc2019[t,]
麦冬$DD <- as.numeric(麦冬$DD)
麦冬$days <- as.numeric(麦冬$days)
麦冬$ds <- 麦冬$DD*麦冬$days
麦冬$ds <- as.numeric(麦冬$ds)
det1<-as.data.frame(麦冬[,c("ID_Name","ds","CMN","days")])
#生成ID_Name为识别号的数据框 
wansc2019_intakesum<-reshape2::dcast(det1, 	
                           ID_Name ~ CMN,
                           value.var = "ds", sum)	
麦冬_wansc2019_intakesum<-as.vector(as.matrix(wansc2019_intakesum$`麦冬`))
wansc2019_dayssum<-reshape2::dcast(det1,
                      ID_Name ~  CMN,
                      value.var = "days",sum)
麦冬_wansc2019_dayssum<-as.vector(as.matrix(wansc2019_dayssum$`麦冬`))
#合并麦冬的消费量和days表格
wansc2019_intakemergedays <- merge(x=wansc2019_intakesum, y=wansc2019_dayssum,
                         by.x="ID_Name",
                         by.y="ID_Name"
)
options(digits = 3)
wansc2019_intakemergedays$standard <- wansc2019_intakemergedays$麦冬.x/wansc2019_intakemergedays$麦冬.y
麦冬_dailyintake <- as.vector(as.matrix(wansc2019_intakemergedays$standard))

# --------retrieve the 麦冬 data of hq2019_raw--------
麦冬 <- hq2019_raw[hq2019_raw$CMN =="麦冬",]
麦冬$DD <- as.numeric(麦冬$DD)
麦冬$days <- as.numeric(麦冬$days)
麦冬$total <- 麦冬$DD*麦冬$days
麦冬$total <- as.numeric(麦冬$total)
det1<-as.data.frame(麦冬[,c("H_Name","total","CMN","days")])
#生成H_Name为识别号的数据框
hq2019_raw_intakesum<-reshape2::dcast(det1, 	
                                  H_Name ~ CMN,
                                  value.var = "total", sum)	
麦冬_hq2019_raw_intakesum<-as.vector(as.matrix(hq2019_raw_intakesum$`麦冬`))
hq2019_raw_dayssum<-reshape2::dcast(det1,
                                H_Name ~  CMN,
                                value.var = "days",sum)
麦冬_hq2019_raw_dayssum<-as.vector(as.matrix(hq2019_raw_dayssum$`麦冬`))
#合并麦冬的消费量和days表格
hq2019_raw_intakemergedays <- merge(x=hq2019_raw_intakesum, y=hq2019_raw_dayssum,
                                by.x="H_Name",
                                by.y="H_Name"
)
options(digits = 3)
hq2019_raw_intakemergedays$standard <- hq2019_raw_intakemergedays$麦冬.x/hq2019_raw_intakemergedays$麦冬.y
麦冬_hq2019_raw_dailyintake <- as.vector(as.matrix(hq2019_raw_intakemergedays$standard))

# --------retrieve the 麦冬 data of kq2019--------
麦冬 <- kq2019[kq2019$CMN =="麦冬",]
麦冬$DD <- as.numeric(麦冬$DD)
麦冬$days <- as.numeric(麦冬$days)
麦冬$total <- 麦冬$DD*麦冬$days
麦冬$total <- as.numeric(麦冬$total)
det1<-as.data.frame(麦冬[,c("Name","total","CMN","days")])
#生成Name为识别号的数据框
kq2019_intakesum<-reshape2::dcast(det1, 	
                                  Name ~ CMN,
                                  value.var = "total", sum)	
麦冬_kq2019_intakesum<-as.vector(as.matrix(kq2019_intakesum$`麦冬`))
kq2019_dayssum<-reshape2::dcast(det1,
                                Name ~  CMN,
                                value.var = "days",sum)
麦冬_kq2019_dayssum<-as.vector(as.matrix(kq2019_dayssum$`麦冬`))
#合并麦冬的消费量和days表格
kq2019_intakemergedays <- merge(x=kq2019_intakesum, y=kq2019_dayssum,
                                by.x="Name",
                                by.y="Name"
)
options(digits = 3)
kq2019_intakemergedays$standard <- kq2019_intakemergedays$麦冬.x/kq2019_intakemergedays$麦冬.y
麦冬_kq2019_dailyintake <- as.vector(as.matrix(kq2019_intakemergedays$standard))

#将三个厂的数据结合
colnames(hq2019_raw_intakemergedays) <- c("Name","intakesum","days","standard")
colnames(wansc2019_intakemergedays) <- c("Name","intakesum","days","standard")
colnames(kq2019_intakemergedays) <- c("Name","intakesum","days","standard")
hq2019_raw_kq2019_intakemergedays <- rbind(hq2019_raw_intakemergedays,kq2019_intakemergedays)
wansc2019_hq2019_raw_kq2019_intakemergedays <- rbind(hq2019_raw_kq2019_intakemergedays,wansc2019_intakemergedays)
colnames(wansc2019_hq2019_raw_kq2019_intakemergedays) <- c("Name","intakesum","days","standard")
write.table(wansc2019_hq2019_raw_kq2019_intakemergedays,file="E:\\R export\\Personal intake disturbution of 麦冬 .csv",row.names = F,col.names = T,sep=",")
```


<center>
```{r 麦冬 quantile calculate, echo=FALSE}
# Calculate the 麦冬 quantile of annual_intake
options(digits=4)
麦冬_wansc2019_hq2019_raw_kq2019_intakesum <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$intakesum))
麦冬_annual_intake<-c(quantile(麦冬_wansc2019_hq2019_raw_kq2019_intakesum, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(麦冬_wansc2019_hq2019_raw_kq2019_intakesum))
# Calculate the 麦冬 quantile of intake_days
麦冬_wansc2019_hq2019_raw_kq2019_dayssum <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$days))
麦冬_intake_days <- c(quantile(麦冬_wansc2019_hq2019_raw_kq2019_dayssum, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(麦冬_wansc2019_hq2019_raw_kq2019_dayssum))
# Calculate the 麦冬 quantile of daily_intake
麦冬_wansc2019_hq2019_raw_kq2019_dailyintake <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$standard))
麦冬_daily_intake <- c(quantile(麦冬_wansc2019_hq2019_raw_kq2019_dailyintake, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(麦冬_hq2019_raw_dailyintake))
```



```{r 党参 data clean, echo=FALSE}

# --------retrieve the 党参 data of wansc2109--------
t <- which(stringr::str_detect(wansc2019$CMN,"党参"))
党参 <- wansc2019[t,]
党参$DD <- as.numeric(党参$DD)
党参$days <- as.numeric(党参$days)
党参$ds <- 党参$DD*党参$days
党参$ds <- as.numeric(党参$ds)
det1<-as.data.frame(党参[,c("ID_Name","ds","CMN","days")])
#生成ID_Name为识别号的数据框 
wansc2019_intakesum<-reshape2::dcast(det1, 	
                           ID_Name ~ CMN,
                           value.var = "ds", sum)	
党参_wansc2019_intakesum<-as.vector(as.matrix(wansc2019_intakesum$`党参`))
wansc2019_dayssum<-reshape2::dcast(det1,
                      ID_Name ~  CMN,
                      value.var = "days",sum)
党参_wansc2019_dayssum<-as.vector(as.matrix(wansc2019_dayssum$`党参`))
#合并党参的消费量和days表格
wansc2019_intakemergedays <- merge(x=wansc2019_intakesum, y=wansc2019_dayssum,
                         by.x="ID_Name",
                         by.y="ID_Name"
)
options(digits = 3)
wansc2019_intakemergedays$standard <- wansc2019_intakemergedays$党参.x/wansc2019_intakemergedays$党参.y
党参_dailyintake <- as.vector(as.matrix(wansc2019_intakemergedays$standard))

# --------retrieve the 党参 data of hq2019_raw--------
党参 <- hq2019_raw[hq2019_raw$CMN =="党参",]
党参$DD <- as.numeric(党参$DD)
党参$days <- as.numeric(党参$days)
党参$total <- 党参$DD*党参$days
党参$total <- as.numeric(党参$total)
det1<-as.data.frame(党参[,c("H_Name","total","CMN","days")])
#生成H_Name为识别号的数据框
hq2019_raw_intakesum<-reshape2::dcast(det1, 	
                                  H_Name ~ CMN,
                                  value.var = "total", sum)	
党参_hq2019_raw_intakesum<-as.vector(as.matrix(hq2019_raw_intakesum$`党参`))
hq2019_raw_dayssum<-reshape2::dcast(det1,
                                H_Name ~  CMN,
                                value.var = "days",sum)
党参_hq2019_raw_dayssum<-as.vector(as.matrix(hq2019_raw_dayssum$`党参`))
#合并党参的消费量和days表格
hq2019_raw_intakemergedays <- merge(x=hq2019_raw_intakesum, y=hq2019_raw_dayssum,
                                by.x="H_Name",
                                by.y="H_Name"
)
options(digits = 3)
hq2019_raw_intakemergedays$standard <- hq2019_raw_intakemergedays$党参.x/hq2019_raw_intakemergedays$党参.y
党参_hq2019_raw_dailyintake <- as.vector(as.matrix(hq2019_raw_intakemergedays$standard))

# --------retrieve the 党参 data of kq2019--------
党参 <- kq2019[kq2019$CMN =="党参",]
党参$DD <- as.numeric(党参$DD)
党参$days <- as.numeric(党参$days)
党参$total <- 党参$DD*党参$days
党参$total <- as.numeric(党参$total)
det1<-as.data.frame(党参[,c("Name","total","CMN","days")])
#生成Name为识别号的数据框
kq2019_intakesum<-reshape2::dcast(det1, 	
                                  Name ~ CMN,
                                  value.var = "total", sum)	
党参_kq2019_intakesum<-as.vector(as.matrix(kq2019_intakesum$`党参`))
kq2019_dayssum<-reshape2::dcast(det1,
                                Name ~  CMN,
                                value.var = "days",sum)
党参_kq2019_dayssum<-as.vector(as.matrix(kq2019_dayssum$`党参`))
#合并党参的消费量和days表格
kq2019_intakemergedays <- merge(x=kq2019_intakesum, y=kq2019_dayssum,
                                by.x="Name",
                                by.y="Name"
)
options(digits = 3)
kq2019_intakemergedays$standard <- kq2019_intakemergedays$党参.x/kq2019_intakemergedays$党参.y
党参_kq2019_dailyintake <- as.vector(as.matrix(kq2019_intakemergedays$standard))

#将三个厂的数据结合
colnames(hq2019_raw_intakemergedays) <- c("Name","intakesum","days","standard")
colnames(wansc2019_intakemergedays) <- c("Name","intakesum","days","standard")
colnames(kq2019_intakemergedays) <- c("Name","intakesum","days","standard")
hq2019_raw_kq2019_intakemergedays <- rbind(hq2019_raw_intakemergedays,kq2019_intakemergedays)
wansc2019_hq2019_raw_kq2019_intakemergedays <- rbind(hq2019_raw_kq2019_intakemergedays,wansc2019_intakemergedays)
colnames(wansc2019_hq2019_raw_kq2019_intakemergedays) <- c("Name","intakesum","days","standard")
write.table(wansc2019_hq2019_raw_kq2019_intakemergedays,file="E:\\R export\\Personal intake disturbution of 党参 .csv",row.names = F,col.names = T,sep=",")
```


<center>
```{r 党参 quantile calculate, echo=FALSE}
# Calculate the 党参 quantile of annual_intake
options(digits=4)
党参_wansc2019_hq2019_raw_kq2019_intakesum <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$intakesum))
党参_annual_intake<-c(quantile(党参_wansc2019_hq2019_raw_kq2019_intakesum, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(党参_wansc2019_hq2019_raw_kq2019_intakesum))
# Calculate the 党参 quantile of intake_days
党参_wansc2019_hq2019_raw_kq2019_dayssum <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$days))
党参_intake_days <- c(quantile(党参_wansc2019_hq2019_raw_kq2019_dayssum, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(党参_wansc2019_hq2019_raw_kq2019_dayssum))
# Calculate the 党参 quantile of daily_intake
党参_wansc2019_hq2019_raw_kq2019_dailyintake <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$standard))
党参_daily_intake <- c(quantile(党参_wansc2019_hq2019_raw_kq2019_dailyintake, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(党参_hq2019_raw_dailyintake))
```



```{r 山药 data clean, echo=FALSE}

# --------retrieve the 山药 data of wansc2109--------
t <- which(stringr::str_detect(wansc2019$CMN,"山药"))
山药 <- wansc2019[t,]
山药$DD <- as.numeric(山药$DD)
山药$days <- as.numeric(山药$days)
山药$ds <- 山药$DD*山药$days
山药$ds <- as.numeric(山药$ds)
det1<-as.data.frame(山药[,c("ID_Name","ds","CMN","days")])
#生成ID_Name为识别号的数据框 
wansc2019_intakesum<-reshape2::dcast(det1, 	
                           ID_Name ~ CMN,
                           value.var = "ds", sum)	
山药_wansc2019_intakesum<-as.vector(as.matrix(wansc2019_intakesum$`山药`))
wansc2019_dayssum<-reshape2::dcast(det1,
                      ID_Name ~  CMN,
                      value.var = "days",sum)
山药_wansc2019_dayssum<-as.vector(as.matrix(wansc2019_dayssum$`山药`))
#合并山药的消费量和days表格
wansc2019_intakemergedays <- merge(x=wansc2019_intakesum, y=wansc2019_dayssum,
                         by.x="ID_Name",
                         by.y="ID_Name"
)
options(digits = 3)
wansc2019_intakemergedays$standard <- wansc2019_intakemergedays$山药.x/wansc2019_intakemergedays$山药.y
山药_dailyintake <- as.vector(as.matrix(wansc2019_intakemergedays$standard))

# --------retrieve the 山药 data of hq2019_raw--------
山药 <- hq2019_raw[hq2019_raw$CMN =="山药",]
山药$DD <- as.numeric(山药$DD)
山药$days <- as.numeric(山药$days)
山药$total <- 山药$DD*山药$days
山药$total <- as.numeric(山药$total)
det1<-as.data.frame(山药[,c("H_Name","total","CMN","days")])
#生成H_Name为识别号的数据框
hq2019_raw_intakesum<-reshape2::dcast(det1, 	
                                  H_Name ~ CMN,
                                  value.var = "total", sum)	
山药_hq2019_raw_intakesum<-as.vector(as.matrix(hq2019_raw_intakesum$`山药`))
hq2019_raw_dayssum<-reshape2::dcast(det1,
                                H_Name ~  CMN,
                                value.var = "days",sum)
山药_hq2019_raw_dayssum<-as.vector(as.matrix(hq2019_raw_dayssum$`山药`))
#合并山药的消费量和days表格
hq2019_raw_intakemergedays <- merge(x=hq2019_raw_intakesum, y=hq2019_raw_dayssum,
                                by.x="H_Name",
                                by.y="H_Name"
)
options(digits = 3)
hq2019_raw_intakemergedays$standard <- hq2019_raw_intakemergedays$山药.x/hq2019_raw_intakemergedays$山药.y
山药_hq2019_raw_dailyintake <- as.vector(as.matrix(hq2019_raw_intakemergedays$standard))

# --------retrieve the 山药 data of kq2019--------
山药 <- kq2019[kq2019$CMN =="山药",]
山药$DD <- as.numeric(山药$DD)
山药$days <- as.numeric(山药$days)
山药$total <- 山药$DD*山药$days
山药$total <- as.numeric(山药$total)
det1<-as.data.frame(山药[,c("Name","total","CMN","days")])
#生成Name为识别号的数据框
kq2019_intakesum<-reshape2::dcast(det1, 	
                                  Name ~ CMN,
                                  value.var = "total", sum)	
山药_kq2019_intakesum<-as.vector(as.matrix(kq2019_intakesum$`山药`))
kq2019_dayssum<-reshape2::dcast(det1,
                                Name ~  CMN,
                                value.var = "days",sum)
山药_kq2019_dayssum<-as.vector(as.matrix(kq2019_dayssum$`山药`))
#合并山药的消费量和days表格
kq2019_intakemergedays <- merge(x=kq2019_intakesum, y=kq2019_dayssum,
                                by.x="Name",
                                by.y="Name"
)
options(digits = 3)
kq2019_intakemergedays$standard <- kq2019_intakemergedays$山药.x/kq2019_intakemergedays$山药.y
山药_kq2019_dailyintake <- as.vector(as.matrix(kq2019_intakemergedays$standard))

#将三个厂的数据结合
colnames(hq2019_raw_intakemergedays) <- c("Name","intakesum","days","standard")
colnames(wansc2019_intakemergedays) <- c("Name","intakesum","days","standard")
colnames(kq2019_intakemergedays) <- c("Name","intakesum","days","standard")
hq2019_raw_kq2019_intakemergedays <- rbind(hq2019_raw_intakemergedays,kq2019_intakemergedays)
wansc2019_hq2019_raw_kq2019_intakemergedays <- rbind(hq2019_raw_kq2019_intakemergedays,wansc2019_intakemergedays)
colnames(wansc2019_hq2019_raw_kq2019_intakemergedays) <- c("Name","intakesum","days","standard")
write.table(wansc2019_hq2019_raw_kq2019_intakemergedays,file="E:\\R export\\Personal intake disturbution of 山药 .csv",row.names = F,col.names = T,sep=",")
```


<center>
```{r 山药 quantile calculate, echo=FALSE}
# Calculate the 山药 quantile of annual_intake
options(digits=4)
山药_wansc2019_hq2019_raw_kq2019_intakesum <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$intakesum))
山药_annual_intake<-c(quantile(山药_wansc2019_hq2019_raw_kq2019_intakesum, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(山药_wansc2019_hq2019_raw_kq2019_intakesum))
# Calculate the 山药 quantile of intake_days
山药_wansc2019_hq2019_raw_kq2019_dayssum <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$days))
山药_intake_days <- c(quantile(山药_wansc2019_hq2019_raw_kq2019_dayssum, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(山药_wansc2019_hq2019_raw_kq2019_dayssum))
# Calculate the 山药 quantile of daily_intake
山药_wansc2019_hq2019_raw_kq2019_dailyintake <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$standard))
山药_daily_intake <- c(quantile(山药_wansc2019_hq2019_raw_kq2019_dailyintake, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(山药_hq2019_raw_dailyintake))
```



```{r 延胡索 data clean, echo=FALSE}

# --------retrieve the 延胡索 data of wansc2109--------
t <- which(stringr::str_detect(wansc2019$CMN,"延胡索"))
延胡索 <- wansc2019[t,]
延胡索$DD <- as.numeric(延胡索$DD)
延胡索$days <- as.numeric(延胡索$days)
延胡索$ds <- 延胡索$DD*延胡索$days
延胡索$ds <- as.numeric(延胡索$ds)
det1<-as.data.frame(延胡索[,c("ID_Name","ds","CMN","days")])
#生成ID_Name为识别号的数据框 
wansc2019_intakesum<-reshape2::dcast(det1, 	
                           ID_Name ~ CMN,
                           value.var = "ds", sum)	
延胡索_wansc2019_intakesum<-as.vector(as.matrix(wansc2019_intakesum$`延胡索`))
wansc2019_dayssum<-reshape2::dcast(det1,
                      ID_Name ~  CMN,
                      value.var = "days",sum)
延胡索_wansc2019_dayssum<-as.vector(as.matrix(wansc2019_dayssum$`延胡索`))
#合并延胡索的消费量和days表格
wansc2019_intakemergedays <- merge(x=wansc2019_intakesum, y=wansc2019_dayssum,
                         by.x="ID_Name",
                         by.y="ID_Name"
)
options(digits = 3)
wansc2019_intakemergedays$standard <- wansc2019_intakemergedays$延胡索.x/wansc2019_intakemergedays$延胡索.y
延胡索_dailyintake <- as.vector(as.matrix(wansc2019_intakemergedays$standard))

# --------retrieve the 延胡索 data of hq2019_raw--------
延胡索 <- hq2019_raw[hq2019_raw$CMN =="延胡索",]
延胡索$DD <- as.numeric(延胡索$DD)
延胡索$days <- as.numeric(延胡索$days)
延胡索$total <- 延胡索$DD*延胡索$days
延胡索$total <- as.numeric(延胡索$total)
det1<-as.data.frame(延胡索[,c("H_Name","total","CMN","days")])
#生成H_Name为识别号的数据框
hq2019_raw_intakesum<-reshape2::dcast(det1, 	
                                  H_Name ~ CMN,
                                  value.var = "total", sum)	
延胡索_hq2019_raw_intakesum<-as.vector(as.matrix(hq2019_raw_intakesum$`延胡索`))
hq2019_raw_dayssum<-reshape2::dcast(det1,
                                H_Name ~  CMN,
                                value.var = "days",sum)
延胡索_hq2019_raw_dayssum<-as.vector(as.matrix(hq2019_raw_dayssum$`延胡索`))
#合并延胡索的消费量和days表格
hq2019_raw_intakemergedays <- merge(x=hq2019_raw_intakesum, y=hq2019_raw_dayssum,
                                by.x="H_Name",
                                by.y="H_Name"
)
options(digits = 3)
hq2019_raw_intakemergedays$standard <- hq2019_raw_intakemergedays$延胡索.x/hq2019_raw_intakemergedays$延胡索.y
延胡索_hq2019_raw_dailyintake <- as.vector(as.matrix(hq2019_raw_intakemergedays$standard))

# --------retrieve the 延胡索 data of kq2019--------
延胡索 <- kq2019[kq2019$CMN =="延胡索",]
延胡索$DD <- as.numeric(延胡索$DD)
延胡索$days <- as.numeric(延胡索$days)
延胡索$total <- 延胡索$DD*延胡索$days
延胡索$total <- as.numeric(延胡索$total)
det1<-as.data.frame(延胡索[,c("Name","total","CMN","days")])
#生成Name为识别号的数据框
kq2019_intakesum<-reshape2::dcast(det1, 	
                                  Name ~ CMN,
                                  value.var = "total", sum)	
延胡索_kq2019_intakesum<-as.vector(as.matrix(kq2019_intakesum$`延胡索`))
kq2019_dayssum<-reshape2::dcast(det1,
                                Name ~  CMN,
                                value.var = "days",sum)
延胡索_kq2019_dayssum<-as.vector(as.matrix(kq2019_dayssum$`延胡索`))
#合并延胡索的消费量和days表格
kq2019_intakemergedays <- merge(x=kq2019_intakesum, y=kq2019_dayssum,
                                by.x="Name",
                                by.y="Name"
)
options(digits = 3)
kq2019_intakemergedays$standard <- kq2019_intakemergedays$延胡索.x/kq2019_intakemergedays$延胡索.y
延胡索_kq2019_dailyintake <- as.vector(as.matrix(kq2019_intakemergedays$standard))

#将三个厂的数据结合
colnames(hq2019_raw_intakemergedays) <- c("Name","intakesum","days","standard")
colnames(wansc2019_intakemergedays) <- c("Name","intakesum","days","standard")
colnames(kq2019_intakemergedays) <- c("Name","intakesum","days","standard")
hq2019_raw_kq2019_intakemergedays <- rbind(hq2019_raw_intakemergedays,kq2019_intakemergedays)
wansc2019_hq2019_raw_kq2019_intakemergedays <- rbind(hq2019_raw_kq2019_intakemergedays,wansc2019_intakemergedays)
colnames(wansc2019_hq2019_raw_kq2019_intakemergedays) <- c("Name","intakesum","days","standard")
write.table(wansc2019_hq2019_raw_kq2019_intakemergedays,file="E:\\R export\\Personal intake disturbution of 延胡索 .csv",row.names = F,col.names = T,sep=",")
```


<center>
```{r 延胡索 quantile calculate, echo=FALSE}
# Calculate the 延胡索 quantile of annual_intake
options(digits=4)
延胡索_wansc2019_hq2019_raw_kq2019_intakesum <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$intakesum))
延胡索_annual_intake<-c(quantile(延胡索_wansc2019_hq2019_raw_kq2019_intakesum, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(延胡索_wansc2019_hq2019_raw_kq2019_intakesum))
# Calculate the 延胡索 quantile of intake_days
延胡索_wansc2019_hq2019_raw_kq2019_dayssum <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$days))
延胡索_intake_days <- c(quantile(延胡索_wansc2019_hq2019_raw_kq2019_dayssum, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(延胡索_wansc2019_hq2019_raw_kq2019_dayssum))
# Calculate the 延胡索 quantile of daily_intake
延胡索_wansc2019_hq2019_raw_kq2019_dailyintake <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$standard))
延胡索_daily_intake <- c(quantile(延胡索_wansc2019_hq2019_raw_kq2019_dailyintake, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(延胡索_hq2019_raw_dailyintake))
```



```{r 黄芩 data clean, echo=FALSE}

# --------retrieve the 黄芩 data of wansc2109--------
t <- which(stringr::str_detect(wansc2019$CMN,"黄芩"))
黄芩 <- wansc2019[t,]
黄芩$DD <- as.numeric(黄芩$DD)
黄芩$days <- as.numeric(黄芩$days)
黄芩$ds <- 黄芩$DD*黄芩$days
黄芩$ds <- as.numeric(黄芩$ds)
det1<-as.data.frame(黄芩[,c("ID_Name","ds","CMN","days")])
#生成ID_Name为识别号的数据框 
wansc2019_intakesum<-reshape2::dcast(det1, 	
                           ID_Name ~ CMN,
                           value.var = "ds", sum)	
黄芩_wansc2019_intakesum<-as.vector(as.matrix(wansc2019_intakesum$`黄芩`))
wansc2019_dayssum<-reshape2::dcast(det1,
                      ID_Name ~  CMN,
                      value.var = "days",sum)
黄芩_wansc2019_dayssum<-as.vector(as.matrix(wansc2019_dayssum$`黄芩`))
#合并黄芩的消费量和days表格
wansc2019_intakemergedays <- merge(x=wansc2019_intakesum, y=wansc2019_dayssum,
                         by.x="ID_Name",
                         by.y="ID_Name"
)
options(digits = 3)
wansc2019_intakemergedays$standard <- wansc2019_intakemergedays$黄芩.x/wansc2019_intakemergedays$黄芩.y
黄芩_dailyintake <- as.vector(as.matrix(wansc2019_intakemergedays$standard))

# --------retrieve the 黄芩 data of hq2019_raw--------
黄芩 <- hq2019_raw[hq2019_raw$CMN =="黄芩",]
黄芩$DD <- as.numeric(黄芩$DD)
黄芩$days <- as.numeric(黄芩$days)
黄芩$total <- 黄芩$DD*黄芩$days
黄芩$total <- as.numeric(黄芩$total)
det1<-as.data.frame(黄芩[,c("H_Name","total","CMN","days")])
#生成H_Name为识别号的数据框
hq2019_raw_intakesum<-reshape2::dcast(det1, 	
                                  H_Name ~ CMN,
                                  value.var = "total", sum)	
黄芩_hq2019_raw_intakesum<-as.vector(as.matrix(hq2019_raw_intakesum$`黄芩`))
hq2019_raw_dayssum<-reshape2::dcast(det1,
                                H_Name ~  CMN,
                                value.var = "days",sum)
黄芩_hq2019_raw_dayssum<-as.vector(as.matrix(hq2019_raw_dayssum$`黄芩`))
#合并黄芩的消费量和days表格
hq2019_raw_intakemergedays <- merge(x=hq2019_raw_intakesum, y=hq2019_raw_dayssum,
                                by.x="H_Name",
                                by.y="H_Name"
)
options(digits = 3)
hq2019_raw_intakemergedays$standard <- hq2019_raw_intakemergedays$黄芩.x/hq2019_raw_intakemergedays$黄芩.y
黄芩_hq2019_raw_dailyintake <- as.vector(as.matrix(hq2019_raw_intakemergedays$standard))

# --------retrieve the 黄芩 data of kq2019--------
黄芩 <- kq2019[kq2019$CMN =="黄芩",]
黄芩$DD <- as.numeric(黄芩$DD)
黄芩$days <- as.numeric(黄芩$days)
黄芩$total <- 黄芩$DD*黄芩$days
黄芩$total <- as.numeric(黄芩$total)
det1<-as.data.frame(黄芩[,c("Name","total","CMN","days")])
#生成Name为识别号的数据框
kq2019_intakesum<-reshape2::dcast(det1, 	
                                  Name ~ CMN,
                                  value.var = "total", sum)	
黄芩_kq2019_intakesum<-as.vector(as.matrix(kq2019_intakesum$`黄芩`))
kq2019_dayssum<-reshape2::dcast(det1,
                                Name ~  CMN,
                                value.var = "days",sum)
黄芩_kq2019_dayssum<-as.vector(as.matrix(kq2019_dayssum$`黄芩`))
#合并黄芩的消费量和days表格
kq2019_intakemergedays <- merge(x=kq2019_intakesum, y=kq2019_dayssum,
                                by.x="Name",
                                by.y="Name"
)
options(digits = 3)
kq2019_intakemergedays$standard <- kq2019_intakemergedays$黄芩.x/kq2019_intakemergedays$黄芩.y
黄芩_kq2019_dailyintake <- as.vector(as.matrix(kq2019_intakemergedays$standard))

#将三个厂的数据结合
colnames(hq2019_raw_intakemergedays) <- c("Name","intakesum","days","standard")
colnames(wansc2019_intakemergedays) <- c("Name","intakesum","days","standard")
colnames(kq2019_intakemergedays) <- c("Name","intakesum","days","standard")
hq2019_raw_kq2019_intakemergedays <- rbind(hq2019_raw_intakemergedays,kq2019_intakemergedays)
wansc2019_hq2019_raw_kq2019_intakemergedays <- rbind(hq2019_raw_kq2019_intakemergedays,wansc2019_intakemergedays)
colnames(wansc2019_hq2019_raw_kq2019_intakemergedays) <- c("Name","intakesum","days","standard")
write.table(wansc2019_hq2019_raw_kq2019_intakemergedays,file="E:\\R export\\Personal intake disturbution of 黄芩 .csv",row.names = F,col.names = T,sep=",")
```


<center>
```{r 黄芩 quantile calculate, echo=FALSE}
# Calculate the 黄芩 quantile of annual_intake
options(digits=4)
黄芩_wansc2019_hq2019_raw_kq2019_intakesum <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$intakesum))
黄芩_annual_intake<-c(quantile(黄芩_wansc2019_hq2019_raw_kq2019_intakesum, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(黄芩_wansc2019_hq2019_raw_kq2019_intakesum))
# Calculate the 黄芩 quantile of intake_days
黄芩_wansc2019_hq2019_raw_kq2019_dayssum <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$days))
黄芩_intake_days <- c(quantile(黄芩_wansc2019_hq2019_raw_kq2019_dayssum, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(黄芩_wansc2019_hq2019_raw_kq2019_dayssum))
# Calculate the 黄芩 quantile of daily_intake
黄芩_wansc2019_hq2019_raw_kq2019_dailyintake <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$standard))
黄芩_daily_intake <- c(quantile(黄芩_wansc2019_hq2019_raw_kq2019_dailyintake, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(黄芩_hq2019_raw_dailyintake))
```



```{r 土鳖虫 data clean, echo=FALSE}

# --------retrieve the 土鳖虫 data of wansc2109--------
t <- which(stringr::str_detect(wansc2019$CMN,"土鳖虫"))
土鳖虫 <- wansc2019[t,]
土鳖虫$DD <- as.numeric(土鳖虫$DD)
土鳖虫$days <- as.numeric(土鳖虫$days)
土鳖虫$ds <- 土鳖虫$DD*土鳖虫$days
土鳖虫$ds <- as.numeric(土鳖虫$ds)
det1<-as.data.frame(土鳖虫[,c("ID_Name","ds","CMN","days")])
#生成ID_Name为识别号的数据框 
wansc2019_intakesum<-reshape2::dcast(det1, 	
                           ID_Name ~ CMN,
                           value.var = "ds", sum)	
土鳖虫_wansc2019_intakesum<-as.vector(as.matrix(wansc2019_intakesum$`土鳖虫`))
wansc2019_dayssum<-reshape2::dcast(det1,
                      ID_Name ~  CMN,
                      value.var = "days",sum)
土鳖虫_wansc2019_dayssum<-as.vector(as.matrix(wansc2019_dayssum$`土鳖虫`))
#合并土鳖虫的消费量和days表格
wansc2019_intakemergedays <- merge(x=wansc2019_intakesum, y=wansc2019_dayssum,
                         by.x="ID_Name",
                         by.y="ID_Name"
)
options(digits = 3)
wansc2019_intakemergedays$standard <- wansc2019_intakemergedays$土鳖虫.x/wansc2019_intakemergedays$土鳖虫.y
土鳖虫_dailyintake <- as.vector(as.matrix(wansc2019_intakemergedays$standard))

# --------retrieve the 土鳖虫 data of hq2019_raw--------
土鳖虫 <- hq2019_raw[hq2019_raw$CMN =="土鳖虫",]
土鳖虫$DD <- as.numeric(土鳖虫$DD)
土鳖虫$days <- as.numeric(土鳖虫$days)
土鳖虫$total <- 土鳖虫$DD*土鳖虫$days
土鳖虫$total <- as.numeric(土鳖虫$total)
det1<-as.data.frame(土鳖虫[,c("H_Name","total","CMN","days")])
#生成H_Name为识别号的数据框
hq2019_raw_intakesum<-reshape2::dcast(det1, 	
                                  H_Name ~ CMN,
                                  value.var = "total", sum)	
土鳖虫_hq2019_raw_intakesum<-as.vector(as.matrix(hq2019_raw_intakesum$`土鳖虫`))
hq2019_raw_dayssum<-reshape2::dcast(det1,
                                H_Name ~  CMN,
                                value.var = "days",sum)
土鳖虫_hq2019_raw_dayssum<-as.vector(as.matrix(hq2019_raw_dayssum$`土鳖虫`))
#合并土鳖虫的消费量和days表格
hq2019_raw_intakemergedays <- merge(x=hq2019_raw_intakesum, y=hq2019_raw_dayssum,
                                by.x="H_Name",
                                by.y="H_Name"
)
options(digits = 3)
hq2019_raw_intakemergedays$standard <- hq2019_raw_intakemergedays$土鳖虫.x/hq2019_raw_intakemergedays$土鳖虫.y
土鳖虫_hq2019_raw_dailyintake <- as.vector(as.matrix(hq2019_raw_intakemergedays$standard))

# --------retrieve the 土鳖虫 data of kq2019--------
土鳖虫 <- kq2019[kq2019$CMN =="土鳖虫",]
土鳖虫$DD <- as.numeric(土鳖虫$DD)
土鳖虫$days <- as.numeric(土鳖虫$days)
土鳖虫$total <- 土鳖虫$DD*土鳖虫$days
土鳖虫$total <- as.numeric(土鳖虫$total)
det1<-as.data.frame(土鳖虫[,c("Name","total","CMN","days")])
#生成Name为识别号的数据框
kq2019_intakesum<-reshape2::dcast(det1, 	
                                  Name ~ CMN,
                                  value.var = "total", sum)	
土鳖虫_kq2019_intakesum<-as.vector(as.matrix(kq2019_intakesum$`土鳖虫`))
kq2019_dayssum<-reshape2::dcast(det1,
                                Name ~  CMN,
                                value.var = "days",sum)
土鳖虫_kq2019_dayssum<-as.vector(as.matrix(kq2019_dayssum$`土鳖虫`))
#合并土鳖虫的消费量和days表格
kq2019_intakemergedays <- merge(x=kq2019_intakesum, y=kq2019_dayssum,
                                by.x="Name",
                                by.y="Name"
)
options(digits = 3)
kq2019_intakemergedays$standard <- kq2019_intakemergedays$土鳖虫.x/kq2019_intakemergedays$土鳖虫.y
土鳖虫_kq2019_dailyintake <- as.vector(as.matrix(kq2019_intakemergedays$standard))

#将三个厂的数据结合
colnames(hq2019_raw_intakemergedays) <- c("Name","intakesum","days","standard")
colnames(wansc2019_intakemergedays) <- c("Name","intakesum","days","standard")
colnames(kq2019_intakemergedays) <- c("Name","intakesum","days","standard")
hq2019_raw_kq2019_intakemergedays <- rbind(hq2019_raw_intakemergedays,kq2019_intakemergedays)
wansc2019_hq2019_raw_kq2019_intakemergedays <- rbind(hq2019_raw_kq2019_intakemergedays,wansc2019_intakemergedays)
colnames(wansc2019_hq2019_raw_kq2019_intakemergedays) <- c("Name","intakesum","days","standard")
write.table(wansc2019_hq2019_raw_kq2019_intakemergedays,file="E:\\R export\\Personal intake disturbution of 土鳖虫 .csv",row.names = F,col.names = T,sep=",")
```


<center>
```{r 土鳖虫 quantile calculate, echo=FALSE}
# Calculate the 土鳖虫 quantile of annual_intake
options(digits=4)
土鳖虫_wansc2019_hq2019_raw_kq2019_intakesum <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$intakesum))
土鳖虫_annual_intake<-c(quantile(土鳖虫_wansc2019_hq2019_raw_kq2019_intakesum, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(土鳖虫_wansc2019_hq2019_raw_kq2019_intakesum))
# Calculate the 土鳖虫 quantile of intake_days
土鳖虫_wansc2019_hq2019_raw_kq2019_dayssum <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$days))
土鳖虫_intake_days <- c(quantile(土鳖虫_wansc2019_hq2019_raw_kq2019_dayssum, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(土鳖虫_wansc2019_hq2019_raw_kq2019_dayssum))
# Calculate the 土鳖虫 quantile of daily_intake
土鳖虫_wansc2019_hq2019_raw_kq2019_dailyintake <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$standard))
土鳖虫_daily_intake <- c(quantile(土鳖虫_wansc2019_hq2019_raw_kq2019_dailyintake, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(土鳖虫_hq2019_raw_dailyintake))
```



```{r 菊花 data clean, echo=FALSE}

# --------retrieve the 菊花 data of wansc2109--------
t <- which(stringr::str_detect(wansc2019$CMN,"菊花"))
菊花 <- wansc2019[t,]
菊花$DD <- as.numeric(菊花$DD)
菊花$days <- as.numeric(菊花$days)
菊花$ds <- 菊花$DD*菊花$days
菊花$ds <- as.numeric(菊花$ds)
det1<-as.data.frame(菊花[,c("ID_Name","ds","CMN","days")])
#生成ID_Name为识别号的数据框 
wansc2019_intakesum<-reshape2::dcast(det1, 	
                           ID_Name ~ CMN,
                           value.var = "ds", sum)	
菊花_wansc2019_intakesum<-as.vector(as.matrix(wansc2019_intakesum$`菊花`))
wansc2019_dayssum<-reshape2::dcast(det1,
                      ID_Name ~  CMN,
                      value.var = "days",sum)
菊花_wansc2019_dayssum<-as.vector(as.matrix(wansc2019_dayssum$`菊花`))
#合并菊花的消费量和days表格
wansc2019_intakemergedays <- merge(x=wansc2019_intakesum, y=wansc2019_dayssum,
                         by.x="ID_Name",
                         by.y="ID_Name"
)
options(digits = 3)
wansc2019_intakemergedays$standard <- wansc2019_intakemergedays$菊花.x/wansc2019_intakemergedays$菊花.y
菊花_dailyintake <- as.vector(as.matrix(wansc2019_intakemergedays$standard))

# --------retrieve the 菊花 data of hq2019_raw--------
菊花 <- hq2019_raw[hq2019_raw$CMN =="菊花",]
菊花$DD <- as.numeric(菊花$DD)
菊花$days <- as.numeric(菊花$days)
菊花$total <- 菊花$DD*菊花$days
菊花$total <- as.numeric(菊花$total)
det1<-as.data.frame(菊花[,c("H_Name","total","CMN","days")])
#生成H_Name为识别号的数据框
hq2019_raw_intakesum<-reshape2::dcast(det1, 	
                                  H_Name ~ CMN,
                                  value.var = "total", sum)	
菊花_hq2019_raw_intakesum<-as.vector(as.matrix(hq2019_raw_intakesum$`菊花`))
hq2019_raw_dayssum<-reshape2::dcast(det1,
                                H_Name ~  CMN,
                                value.var = "days",sum)
菊花_hq2019_raw_dayssum<-as.vector(as.matrix(hq2019_raw_dayssum$`菊花`))
#合并菊花的消费量和days表格
hq2019_raw_intakemergedays <- merge(x=hq2019_raw_intakesum, y=hq2019_raw_dayssum,
                                by.x="H_Name",
                                by.y="H_Name"
)
options(digits = 3)
hq2019_raw_intakemergedays$standard <- hq2019_raw_intakemergedays$菊花.x/hq2019_raw_intakemergedays$菊花.y
菊花_hq2019_raw_dailyintake <- as.vector(as.matrix(hq2019_raw_intakemergedays$standard))

# --------retrieve the 菊花 data of kq2019--------
菊花 <- kq2019[kq2019$CMN =="菊花",]
菊花$DD <- as.numeric(菊花$DD)
菊花$days <- as.numeric(菊花$days)
菊花$total <- 菊花$DD*菊花$days
菊花$total <- as.numeric(菊花$total)
det1<-as.data.frame(菊花[,c("Name","total","CMN","days")])
#生成Name为识别号的数据框
kq2019_intakesum<-reshape2::dcast(det1, 	
                                  Name ~ CMN,
                                  value.var = "total", sum)	
菊花_kq2019_intakesum<-as.vector(as.matrix(kq2019_intakesum$`菊花`))
kq2019_dayssum<-reshape2::dcast(det1,
                                Name ~  CMN,
                                value.var = "days",sum)
菊花_kq2019_dayssum<-as.vector(as.matrix(kq2019_dayssum$`菊花`))
#合并菊花的消费量和days表格
kq2019_intakemergedays <- merge(x=kq2019_intakesum, y=kq2019_dayssum,
                                by.x="Name",
                                by.y="Name"
)
options(digits = 3)
kq2019_intakemergedays$standard <- kq2019_intakemergedays$菊花.x/kq2019_intakemergedays$菊花.y
菊花_kq2019_dailyintake <- as.vector(as.matrix(kq2019_intakemergedays$standard))

#将三个厂的数据结合
colnames(hq2019_raw_intakemergedays) <- c("Name","intakesum","days","standard")
colnames(wansc2019_intakemergedays) <- c("Name","intakesum","days","standard")
colnames(kq2019_intakemergedays) <- c("Name","intakesum","days","standard")
hq2019_raw_kq2019_intakemergedays <- rbind(hq2019_raw_intakemergedays,kq2019_intakemergedays)
wansc2019_hq2019_raw_kq2019_intakemergedays <- rbind(hq2019_raw_kq2019_intakemergedays,wansc2019_intakemergedays)
colnames(wansc2019_hq2019_raw_kq2019_intakemergedays) <- c("Name","intakesum","days","standard")
write.table(wansc2019_hq2019_raw_kq2019_intakemergedays,file="E:\\R export\\Personal intake disturbution of 菊花 .csv",row.names = F,col.names = T,sep=",")
```


<center>
```{r 菊花 quantile calculate, echo=FALSE}
# Calculate the 菊花 quantile of annual_intake
options(digits=4)
菊花_wansc2019_hq2019_raw_kq2019_intakesum <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$intakesum))
菊花_annual_intake<-c(quantile(菊花_wansc2019_hq2019_raw_kq2019_intakesum, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(菊花_wansc2019_hq2019_raw_kq2019_intakesum))
# Calculate the 菊花 quantile of intake_days
菊花_wansc2019_hq2019_raw_kq2019_dayssum <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$days))
菊花_intake_days <- c(quantile(菊花_wansc2019_hq2019_raw_kq2019_dayssum, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(菊花_wansc2019_hq2019_raw_kq2019_dayssum))
# Calculate the 菊花 quantile of daily_intake
菊花_wansc2019_hq2019_raw_kq2019_dailyintake <- as.vector(as.matrix(wansc2019_hq2019_raw_kq2019_intakemergedays$standard))
菊花_daily_intake <- c(quantile(菊花_wansc2019_hq2019_raw_kq2019_dailyintake, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(菊花_hq2019_raw_dailyintake))
```

```{r intakesum of all traditional medicine quantile calculate, echo=FALSE}
total <- read.csv2("E:\\R export\\三家药厂个人摄入量 (H_Name,ID_Name,Name).csv",header = T, sep =",",check.names=F)
total <- total[,1:5]
colnames(total) <- c("ID","dayssum","intakesum","datasource","dailyintake")
total <- as.data.frame(lapply(total[,c("dayssum","intakesum","dailyintake")],as.numeric))
# Calculate the Chinese medicine quantile of annual_intake
options(digits=4)
total_intakesum <- as.vector(as.matrix(total$intakesum))
Chinesemedicine_annual_intake<-c(quantile(total_intakesum, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(total_intakesum))
# Calculate the Chinese medicine quantile of intake_days
total_dayssum <- as.vector(as.matrix(total$days))
Chinesemedicine_intake_days <- c(quantile(total_dayssum, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(total_dayssum))
# Calculate the Chinese medicine quantile of daily_intake
total_dailyintake <- as.vector(as.matrix(total$dailyintake))
Chinesemedicine_daily_intake <- c(quantile(total_dailyintake, probs = c(0.05,0.5,0.90,0.95,0.975)), mean(total_dailyintake))
```
```{r The binding of three table, echo=FALSE}
options(digits=1)
# binding of number of Consumers
options(scipen = 200)
黄芪<- read.csv2("E:/R export/Personal intake disturbution of 黄芪 .csv",header = T, sep =",",check.names=F)
Consumers_of_黄芪 <- nrow(黄芪)
薏苡仁<- read.csv2("E:/R export/Personal intake disturbution of 薏苡仁 .csv",header = T, sep =",",check.names=F)
Consumers_of_薏苡仁 <- nrow(薏苡仁)
酸枣仁<- read.csv2("E:/R export/Personal intake disturbution of 酸枣仁 .csv",header = T, sep =",",check.names=F)
Consumers_of_酸枣仁 <- nrow(酸枣仁)
白术<- read.csv2("E:/R export/Personal intake disturbution of 白术 .csv",header = T, sep =",",check.names=F)
Consumers_of_白术 <- nrow(白术)
三七<- read.csv2("E:/R export/Personal intake disturbution of 三七 .csv",header = T, sep =",",check.names=F)
Consumers_of_三七 <- nrow(三七)
丹参<- read.csv2("E:/R export/Personal intake disturbution of 丹参 .csv",header = T, sep =",",check.names=F)
Consumers_of_丹参 <- nrow(丹参)
人参<- read.csv2("E:/R export/Personal intake disturbution of 人参 .csv",header = T, sep =",",check.names=F)
Consumers_of_人参 <- nrow(人参)
枸杞<- read.csv2("E:/R export/Personal intake disturbution of 枸杞 .csv",header = T, sep =",",check.names=F)
Consumers_of_枸杞 <- nrow(枸杞)
金银花<- read.csv2("E:/R export/Personal intake disturbution of 金银花 .csv",header = T, sep =",",check.names=F)
Consumers_of_金银花 <- nrow(金银花)
麦冬<- read.csv2("E:/R export/Personal intake disturbution of 麦冬 .csv",header = T, sep =",",check.names=F)
Consumers_of_麦冬 <- nrow(麦冬)
党参<- read.csv2("E:/R export/Personal intake disturbution of 党参 .csv",header = T, sep =",",check.names=F)
Consumers_of_党参 <- nrow(党参)
山药<- read.csv2("E:/R export/Personal intake disturbution of 山药 .csv",header = T, sep =",",check.names=F)
Consumers_of_山药 <- nrow(山药)
延胡索<- read.csv2("E:/R export/Personal intake disturbution of 延胡索 .csv",header = T, sep =",",check.names=F)
Consumers_of_延胡索 <- nrow(延胡索)
黄芩<- read.csv2("E:/R export/Personal intake disturbution of 黄芩 .csv",header = T, sep =",",check.names=F)
Consumers_of_黄芩 <- nrow(黄芩)
土鳖虫<- read.csv2("E:/R export/Personal intake disturbution of 土鳖虫 .csv",header = T, sep =",",check.names=F)
Consumers_of_土鳖虫 <- nrow(土鳖虫)
菊花<- read.csv2("E:/R export/Personal intake disturbution of 菊花 .csv",header = T, sep =",",check.names=F)
Consumers_of_菊花 <- nrow(菊花)
Consumers_of_TCM <- c(Consumers_of_黄芪,Consumers_of_薏苡仁,Consumers_of_酸枣仁,Consumers_of_白术,Consumers_of_三七,Consumers_of_丹参,Consumers_of_人参,Consumers_of_枸杞,Consumers_of_金银花,Consumers_of_麦冬,Consumers_of_党参,Consumers_of_山药,Consumers_of_延胡索,Consumers_of_黄芩,Consumers_of_土鳖虫,Consumers_of_菊花)
Consumers_of_TCM <- as.data.frame(Consumers_of_TCM)
rownames(Consumers_of_TCM) <- c("Astragalus membranaceus", "Coix lacryma-jobi", "Ziziphus jujuba", "Atractylodes macrocephala", "Parnx notoginseng", "Salvia miltiorrhiza", "Panax ginseng", "Lycium Barbarum", "Lonicera japonica", "Ophiopogon japonicus", "Changium smyrnioides", "Corydalis yanhusuo", "Dioscorea opposita", "Scutellaria baicalensis", "Eupolyphaga sinensis Walker", "Chrysanthemum morifolium")

kable(Consumers_of_TCM)%>%
  kable_styling(full_width = F,bootstrap_options = c("striped", "hover", "condensed", "responsive"))
# The binding of annual_intake
annual_intake <- rbind(黄芪_annual_intake,薏苡仁_annual_intake)
annual_intake <- rbind(annual_intake,酸枣仁_annual_intake)
annual_intake <- rbind(annual_intake,白术_annual_intake)
annual_intake <- rbind(annual_intake,三七_annual_intake)
annual_intake <- rbind(annual_intake,丹参_annual_intake)
annual_intake <- rbind(annual_intake,人参_annual_intake)
annual_intake <- rbind(annual_intake,枸杞_annual_intake)
annual_intake <- rbind(annual_intake,金银花_annual_intake)
annual_intake <- rbind(annual_intake,麦冬_annual_intake)
annual_intake <- rbind(annual_intake,党参_annual_intake)
annual_intake <- rbind(annual_intake,山药_annual_intake)
annual_intake <- rbind(annual_intake,延胡索_annual_intake)
annual_intake <- rbind(annual_intake,黄芩_annual_intake)
annual_intake <- rbind(annual_intake,土鳖虫_annual_intake)
annual_intake <- rbind(annual_intake,菊花_annual_intake)
annual_intake <- rbind(annual_intake,Chinesemedicine_annual_intake)
colnames(annual_intake) <- c("P5","P50","P90","P95","P97.5","mean")
rownames(annual_intake) <- c("Astragalus membranaceus", "Coix lacryma-jobi", "Ziziphus jujuba", "Atractylodes macrocephala", "Parnx notoginseng", "Salvia miltiorrhiza", "Panax ginseng", "Lycium Barbarum", "Lonicera japonica", "Ophiopogon japonicus", "Changium smyrnioides", "Corydalis yanhusuo", "Dioscorea opposita", "Scutellaria baicalensis", "Eupolyphaga sinensis Walker", "Chrysanthemum morifolium","Total of chinese medicine")

kable(annual_intake)%>%
  kable_styling(full_width = F,bootstrap_options = c("striped", "hover", "condensed", "responsive"))
# The binding of intake_days
intake_days <- rbind(黄芪_intake_days,薏苡仁_intake_days)
intake_days <- rbind(intake_days,酸枣仁_intake_days)
intake_days <- rbind(intake_days,白术_intake_days)
intake_days <- rbind(intake_days,三七_intake_days)
intake_days <- rbind(intake_days,丹参_intake_days)
intake_days <- rbind(intake_days,人参_intake_days)
intake_days <- rbind(intake_days,枸杞_intake_days)
intake_days <- rbind(intake_days,金银花_intake_days)
intake_days <- rbind(intake_days,麦冬_intake_days)
intake_days <- rbind(intake_days,党参_intake_days)
intake_days <- rbind(intake_days,山药_intake_days)
intake_days <- rbind(intake_days,延胡索_intake_days)
intake_days <- rbind(intake_days,黄芩_intake_days)
intake_days <- rbind(intake_days,土鳖虫_intake_days)
intake_days <- rbind(intake_days,菊花_intake_days)
intake_days <- rbind(intake_days,Chinesemedicine_intake_days)
colnames(intake_days) <- c("P5","P50","P90","P95","P97.5","mean")
rownames(intake_days) <- c("Astragalus membranaceus", "Coix lacryma-jobi", "Ziziphus jujuba", "Atractylodes macrocephala", "Parnx notoginseng", "Salvia miltiorrhiza", "Panax ginseng", "Lycium Barbarum", "Lonicera japonica", "Ophiopogon japonicus", "Changium smyrnioides", "Corydalis yanhusuo", "Dioscorea opposita", "Scutellaria baicalensis", "Eupolyphaga sinensis Walker", "Chrysanthemum morifolium","Total of chinese medicine")
kable(intake_days)%>%
  kable_styling(full_width = F,bootstrap_options = c("striped", "hover", "condensed", "responsive"))

# The binding of daily_intake
daily_intake <- rbind(黄芪_daily_intake,薏苡仁_daily_intake)
daily_intake <- rbind(daily_intake,酸枣仁_daily_intake)
daily_intake <- rbind(daily_intake,白术_daily_intake)
daily_intake <- rbind(daily_intake,三七_daily_intake)
daily_intake <- rbind(daily_intake,丹参_daily_intake)
daily_intake <- rbind(daily_intake,人参_daily_intake)
daily_intake <- rbind(daily_intake,枸杞_daily_intake)
daily_intake <- rbind(daily_intake,金银花_daily_intake)
daily_intake <- rbind(daily_intake,麦冬_daily_intake)
daily_intake <- rbind(daily_intake,党参_daily_intake)
daily_intake <- rbind(daily_intake,山药_daily_intake)
daily_intake <- rbind(daily_intake,延胡索_daily_intake)
daily_intake <- rbind(daily_intake,黄芩_daily_intake)
daily_intake <- rbind(daily_intake,土鳖虫_daily_intake)
daily_intake <- rbind(daily_intake,菊花_daily_intake)
daily_intake <- rbind(daily_intake,Chinesemedicine_daily_intake)
colnames(daily_intake) <- c("P5","P50","P90","P95","P97.5","mean")
rownames(daily_intake) <- c("Astragalus membranaceus", "Coix lacryma-jobi", "Ziziphus jujuba", "Atractylodes macrocephala", "Parnx notoginseng", "Salvia miltiorrhiza", "Panax ginseng", "Lycium Barbarum", "Lonicera japonica", "Ophiopogon japonicus", "Changium smyrnioides", "Corydalis yanhusuo", "Dioscorea opposita", "Scutellaria baicalensis", "Eupolyphaga sinensis Walker", "Chrysanthemum morifolium","Total of chinese medicine")

kable(daily_intake)%>%
  kable_styling(full_width = F,bootstrap_options = c("striped", "hover", "condensed", "responsive"))

```
<center><font face="黑体" size=2>fig 1 The intake situation Graph of Chinese medicine in Shanghai</center></font>
```{r The intake situation, echo=FALSE}
# data collection
total <- read.csv2("E:\\R export\\三家药厂个人摄入量 (H_Name,ID_Name,Name).csv",header = T, sep =",",check.names=F)
total <- total[,1:5]
colnames(total) <- c("patient","intakedays","intakesum","Data Sources","dailyintake")
total$patient <- str_c("patient",rownames(total))
write.table(wansc2019_hq2019_raw_kq2019_intakemergedays,file="E:\\R export\\tcm\\Individual intake situation.csv",row.names = F,col.names = T,sep=",")
# Calculate the quantile of intakesum
options(scipen=200)
total$intakesum <- as.numeric(total$intakesum)
total_intakesum <- as.vector(as.matrix(total$intakesum))
total_intakesum_quantile <- c(quantile(total_intakesum, probs = c(0.05,0.5,0.95)), mean(total_intakesum))
#plot
hist(total_intakesum,
        main="",
        xlab="intakesum(g)",ylab="Number of people",
        col = 'darkgray', border = 'darkgray',cex.axis=0.7,cex.lab=0.7,
        xlim=c(0,2*total_intakesum_quantile[3]),ylim=c(0,max(table(total_intakesum))*50),
        breaks = 2*total_intakesum_quantile[3]/300)
#画直线

abline(v = total_intakesum_quantile,lty = 3,lwd = 2,col=c("green","yellow","red","orange"))
#加标注
A4<-paste(c("p5     ","p50   ","p95   ","mean"),
          c(round(total_intakesum_quantile[1:2],4),round(total_intakesum_quantile[3],4),round(total_intakesum_quantile[4],0)),
          sep=":")
legend("topright",legend=A4, 
       col=c("green","yellow","red","orange"),lty=c(2,2,2,2),lwd=c(2,2,2,2),cex=0.6,bty = "o")
#线上写文字
text(c(total_intakesum_quantile[1]-2.5*total_intakesum_quantile[3]/50,
           total_intakesum_quantile[2]+2.5*total_intakesum_quantile[3]/30,
           total_intakesum_quantile[4]+2.5*total_intakesum_quantile[3]/20,
           total_intakesum_quantile[3]-2.5*total_intakesum_quantile[3]/30),
     max(table(total_intakesum))*50,
     c("p5","p50","mean","p95"),cex=0.7)
```